deploy-disconnected-registry/common.sh
deploy-disconnected-registry/config.yml
deploy-disconnected-registry/deploy.sh
deploy-disconnected-registry/manifests/deployment.yaml
deploy-disconnected-registry/manifests/pvc-registry.yaml
deploy-disconnected-registry/manifests/service.yaml
deploy-disconnected-registry/ocp-sync.sh
deploy-disconnected-registry/olm-sync.sh

- Registry deployment
- Changed Authentication
- Integrated with TLS Certificates
- OLM sync verified
- OCP syn not verified

Adding deployment of New Embedded Internal Registry

---

.github/workflows/deploy-ztp-relocatable.yml
deploy-acm/deploy.sh
deploy-disconnected-registry/common.sh
deploy-disconnected-registry/deploy.sh
deploy-disconnected-registry/ocp-sync.sh
deploy-disconnected-registry/olm-sync.sh
deploy-httpd-server/deploy.sh
deploy-hub-configs/deploy.sh
deploy-spoke/deploy.sh
deploy-spoke/render_spokes.sh
shared-utils/common.sh
shared-utils/verify_preflight.sh
shared-utils/wait_for_deployment.sh

Signed-off-by: Pablo Iranzo Gómez <Pablo.Iranzo@gmail.com>

More common vars

---

hack/deploy-hub-local/build.sh

Adds config section and spokes section for build.sh

Fix configuration creation

---

.github/workflows/deploy-ztp-relocatable.yml
deploy-disconnected-registry/deploy.sh
deploy-disconnected-registry/manifests/machine-config-certs.yaml
deploy-disconnected-registry/olm-sync.sh
deploy-disconnected-registry/update-global-pullsecret.sh

- Machine config created using templates and subenv to update the ca in master nodes
- Created bypass for hub and spokes
@jparrill needs review

add machine config update ca local registry

---

deploy-disconnected-registry/ocp-sync.sh
deploy-disconnected-registry/olm-sync.sh
deploy-disconnected-registry/verify_ocp_sync.sh
deploy-disconnected-registry/verify_olm_sync.sh
deploy-ocs/verify.sh

- verify in ocs step
- verify for registry sync into spokes: verify, verify_ocp_sync and verify_olm_sync

Verify ocs and spoke sync

---

.github/workflows/deploy-ztp-relocatable.yml
.pre-commit-config.yaml
deploy-worker/render_worker.sh
hack/deploy-hub-local/build.sh
hack/deploy-hub-local/create-vm.yml

Deploy workers for each spoke to be handled as BMH

WIP: Deploy workers

---

deploy-metallb/deploy.sh

Logic done, still things to do and verify external access

---

deploy-disconnected-registry/deploy.sh
deploy-disconnected-registry/olm-sync.sh
pipelines/resources/deploy-ztp-hub.yaml
pipelines/resources/hub/hub-deploy-disconnected-registry.yaml
pipelines/resources/spokes/spoke-deploy-disconnected-registry-spokes.yaml
shared-utils/common.sh
shared-utils/verify_preflight.sh

Only perform skopeo with failed images

Skopeo when needed

---

pipelines/bootstrap.sh

Removing redundant line. The variable
was already defined.
- Versions:
- Hardware:

Remove duplicate line.

---

Makefile
pipelines/resources/common/common-pre-flight.yaml
pipelines/resources/deploy-ztp-hub.yaml
pipelines/resources/deploy-ztp-spokes.yaml
pipelines/resources/hub/hub-deploy-acm.yaml
pipelines/resources/hub/hub-deploy-disconnected-registry.yaml
pipelines/resources/hub/hub-deploy-httpd-server.yaml
pipelines/resources/hub/hub-deploy-hub-config.yaml
pipelines/resources/hub/hub-deploy-icsp.yaml
pipelines/resources/hub/hub-save-config.yaml
pipelines/resources/spokes/spoke-deploy-disconnected-registry-spokes.yaml
pipelines/resources/spokes/spoke-deploy-icsp-spokes-post.yaml
pipelines/resources/spokes/spoke-deploy-icsp-spokes-pre.yaml
pipelines/resources/spokes/spoke-deploy-metallb.yaml
pipelines/resources/spokes/spoke-deploy-ocs.yaml
pipelines/resources/spokes/spoke-deploy-spoke.yaml
pipelines/resources/spokes/spoke-deploy-ui.yaml
pipelines/resources/spokes/spoke-deploy-workers.yaml
pipelines/resources/spokes/spoke-detach-cluster.yaml
pipelines/resources/spokes/spoke-restore-hub-config.yaml

- https://issues.redhat.com/browse/MGMT-9439

MGMT-9439 - Container Image update

---

deploy-spoke/csr_autoapprover.sh

Remove the kubeconfig path at the end of the pipeline in order to be removed by the systemd script
Fixes # 
- Versions:
- Hardware:

remove kubeconfig path

---

hack/deploy-hub-local/helpers/redfish.py

fix redfish.py for hpe boxes
- [X ] Bug fix (non-breaking change which fixes an issue)
- Versions:
- Hardware:

fix redfish.py for hpe boxes

---

images/Containerfile.UI

The UI Dockerfile downloads a lot of JavaScript dependencies from the npmjs registry. They can occasionally fail causing the whole script to fail. This patch adds 3 attempts to retry to reduce flakiness.
- Versions:
- Hardware:

UI: Reduce flakiness of the npm in Containerfile.UI Dockerfile

---

pipelines/bootstrap.sh

This patch add yq if it's missing.
Note: Linux binary only.
- Versions:
- Hardware:

Add yq if missing.

---

ui/frontend/src/components/FinalPage/__snapshots__/FinalPage.test.tsx.snap
ui/frontend/src/components/FinalPage/__snapshots__/FinalPageSummary.test.tsx.snap

UI unit test snapshot got updated

UI: update unit test snapshots

---

ui/frontend/src/components/PasswordPage/PasswordSelector.tsx
ui/frontend/src/components/PasswordPage/__snapshots__/PasswordPage.test.tsx.snap
ui/frontend/src/components/PersistPage/persistIdentityProvider.ts
ui/frontend/src/components/WelcomePage/initialDataLoad.ts
ui/frontend/src/resources/oauth.ts

Instead of former metallb-ingress loadBalancerIP presence which appeared
to be added by factory.
- Versions:
- Hardware:

UI: Decide Wizard vs Settings page based on Htpasswd IDP presence

---

.github/workflows/testing-pr.yml
hack/deploy-hub-local/build-spoke.sh

debugging pipe for PR

---

.pre-commit-config.yaml
deploy-metallb/deploy.sh
deploy-spoke/render_spokes.sh
finish-deployment/deploy.sh
shared-utils/common.sh

Attempt to auto calculate number of master
Closes #89

Grab automatically the number of masters

---

.pre-commit-config.yaml
deploy-metallb/deploy.sh
deploy-spoke/render_spokes.sh
finish-deployment/deploy.sh
shared-utils/common.sh

Reverts rh-ecosystem-edge/ztp-pipeline-relocatable#91

Revert "Grab automatically the number of masters"

---

ui/frontend/src/components/ApiAddressPage/ApiAddressSelector.test.tsx
ui/frontend/src/components/ApiAddressPage/__snapshots__/ApiAddressPage.test.tsx.snap
ui/frontend/src/components/ApiAddressPage/__snapshots__/ApiAddressSelector.test.tsx.snap
ui/frontend/src/components/IngressIpPage/IngressIpSelector.test.tsx
ui/frontend/src/components/IngressIpPage/__snapshots__/IngressIpPage.test.tsx.snap
ui/frontend/src/components/IngressIpPage/__snapshots__/IngressIpSelector.test.tsx.snap
ui/frontend/src/components/IpTriplet/IpTriplet.tsx
ui/frontend/src/components/Settings/Settings.test.tsx
ui/frontend/src/components/Settings/__snapshots__/Settings.test.tsx.snap

UI: the IP triplets are shown without leading zeroes.
- Versions:
- Hardware:

MGMT-9523: Remove leading zeroes in IP triplets

---

ui/frontend/src/components/DownloadSshKeyPage/DownloadSshKey.tsx
ui/frontend/src/components/UsernamePage/UsernamePage.test.tsx
ui/frontend/src/components/UsernamePage/UsernamePage.tsx
ui/frontend/src/components/UsernamePage/UsernameSelector.test.tsx
ui/frontend/src/components/UsernamePage/UsernameSelector.tsx
ui/frontend/src/components/UsernamePage/__snapshots__/UsernamePage.test.tsx.snap
ui/frontend/src/components/UsernamePage/__snapshots__/UsernameSelector.test.tsx.snap
ui/frontend/src/components/WelcomePage/WelcomeBottom.tsx
ui/frontend/src/components/WelcomePage/WelcomePage.test.tsx
ui/frontend/src/components/WelcomePage/__snapshots__/WelcomePage.test.tsx.snap
ui/frontend/src/components/WelcomePage/initialDataLoad.ts
ui/frontend/src/resources/consoleUrl.ts
ui/frontend/src/test-utils.ts

UI unit tests - Username and Welcome page

---

.github/workflows/testing-pr.yml
.pre-commit-config.yaml
deploy-metallb/deploy.sh
deploy-spoke/render_spokes.sh
finish-deployment/deploy.sh

Automaster

---

deploy-disconnected-registry/olm-sync.sh

There's an error working with podman.
Providing extra argument in attempt
to overcome them.
- Versions:
- Hardware:

Extra arguments to overcome an error.

---

.github/workflows/testing-pr.yml

Use 'skip-ci' to bypass CI checks

Run CI only when 'skip-ci' is not present

---

documentation/ztp-for-factories/ztp-for-factory-prerequisites.adoc

Some enhancement to the storage section

---

documentation/ztp-for-factories/ztp-for-factory-troubleshooting.adoc

Doc enhancement to the troubleshooting section

---

documentation/ztp-for-factories/ztp-for-factory-installation-workflow.adoc

Some enhancement to the flow section

---

documentation/ztp-for-factories/ztp-for-factory-pipeline-hub.adoc

Pipeline hub doc enhancements

---

.github/labels.yml
.github/workflows/label.yml

Autolabels issues based on patterns and folders used

Add autolabelling GHA

---

deploy-disconnected-registry/olm-sync.sh

Seems like the condition prevents the copy.
- Versions:
- Hardware:

Unconditionally copy pull-secret.

---

.github/labels.yml

Update labels to use

---

documentation/ztp-for-factories/ztp-for-factory-prerequisites.adoc
documentation/ztp-for-factories/ztp-for-factory-spokes-yaml.adoc
examples/config.yaml

Add mention to ignore interfaces feature

Ignore Network interfaces

---

ui/frontend/src/components/PersistPage/constants.ts
ui/frontend/src/components/PersistPage/persist.ts
ui/frontend/src/components/PersistPage/persistIdentityProvider.ts
ui/frontend/src/components/UsernamePage/UsernameSelector.tsx
ui/frontend/src/components/UsernamePage/__snapshots__/UsernamePage.test.tsx.snap
ui/frontend/src/components/UsernamePage/__snapshots__/UsernameSelector.test.tsx.snap
ui/frontend/src/resources/secret.ts

The kubeadmin's password is revoked once new user with cluster-admin role is created.
- Versions:
- Hardware:

MGMT-9698 Revoke kubeadmin password

---

ui/frontend/src/components/WelcomePage/initialDataLoad.ts
ui/frontend/src/resources/service.ts

Covers the case after unboxing when loadBalancerIP is not yet explicitly set.
- Versions:
- Hardware:

UI: Read api/ingress IP from status as a fallback

---

deploy-disconnected-registry/olm-sync.sh
pipelines/resources/hub/hub-deploy-disconnected-registry.yaml
pipelines/resources/spokes/spoke-deploy-disconnected-registry-spokes.yaml

Improving the timing using multi-threading with tekton pipeline instead of only mono-thread. 
Testing internally with the result expected (from 1h:30 to 30 min ) 
- Versions: 4.9
- Hardware: lab cnf12

Resources tekton - multithreading

---

deploy-spoke/configure_disconnected.sh

Do not hardcode # of hosts
Partial #126

Get number of hosts to wait for instead of hardcoding them

---

documentation/ztp-for-factories/ztp-for-factory-prerequisites.adoc
examples/config.yaml
hack/deploy-hub-local/build-spoke.sh
hack/deploy-hub-local/create-vm.yml
shared-utils/verify_preflight-spokes.sh

Adds mandatory root_disk configuration to the examples, documentation and preflight verification

Add mandatory root_disk

---

deploy-ocs/deploy.sh

Nuke disks before installation of OCS for the Spokes
Closes #85

Nuke disks

---

deploy-ocs/deploy.sh
deploy-ocs/manifests/04-OCS-StorageCluster.yaml

per master.
Although a count of 1 is legal, eventually we need more space
and thus we need to utilize more disks.
- Versions:
- Hardware:

The storageDeviceSet count should match the number of disks

---

hack/deploy-hub-local/build-hub.sh
hack/deploy-hub-local/build-spoke.sh
hack/deploy-hub-local/lab-nfs.sh
hack/deploy-hub-local/nfs.yml
hack/deploy-hub-local/sno-metal3.yml

WIP since this depends on the migration to 4.10
- Versions:
- Hardware:

MGMT-9715 Hub sno

---

.github/workflows/testing-pr.yml

add 'test-ci'label to pipe

---

ui/backend/src/endpoints/htpasswd.ts

Text of logs in the /htpasswd enpoint are more clear now.
- Versions:
- Hardware:

Improve logging of the htpasswd endpoint

---

ui/frontend/src/components/WelcomePage/initialDataLoad.ts

The Ingress/API IP addresses were not correctly loaded for factory-set cluster

Fix initial data load of IPs

---

deploy-spoke/render_spokes.sh

we may get "invalid input" otherwise.
- Versions:
- Hardware:

Disable line wrapping for base64

---

.github/workflows/build-and-push-release.yml
.github/workflows/build-and-push-tags.yml
.github/workflows/testing-pr.yml
Makefile

add make structure with basic target to deploy all use cases

---

Makefile
images/Containerfile.pipeline

reopen PR #171 
This PR is enhancement for the build-pipe image
1. add layering for increment builds / push / pull
2. removing duplicated downloads for `kubectl`
3.  add `/var/cache/yum` delete after installation
- Versions:
- Hardware:

[enhancement] optimize build-pipe image

---

pipelines/bootstrap.sh

Adding some checks to bootstrap 
1.  check if `oc` client exists 
2.  check if script run as root 
- Versions:
- Hardware:

adding checks bootstrap.sh

---

documentation/ztp-for-factories/ztp-for-factory-development.adoc
documentation/ztp-for-factories/ztp-for-factory-installation-workflow.adoc
documentation/ztp-for-factories/ztp-for-factory-pipeline-hub.adoc

We no longer use this param.
- Versions:
- Hardware:

Removing the mentioning of git-revision

---

deploy-spoke/render_spokes.sh

Only add the static route when deploying an SNO edge-cluster
- Versions:
- Hardware:

Add a second default route only for SNO Spokes

---

deploy-metallb/deploy.sh

Change the way we are getting the agent and IP for metallb to make sure that we get an agent that is also a master. This helps in cases when masters+workers are deployed together.
- Versions:
- Hardware:

Change way we get agent IP for metallb

---

Makefile

Add a clean target to add cleaning steps

---

Makefile
shared-utils/wait_for_sno_mco.sh

With MCO in SNO we're loosing the API to continue with the pipeline. With this PR we deploy a new script to monitorize the api until is restarted to relaunch the make target again 
Fixes [MGMT-9977](https://issues.redhat.com/browse/MGMT-9977)
- Versions:
- Hardware:

MGMT-9977-hub-sno-mco

---

ui/backend/src/endpoints/user.ts

UI: Add more logging to the "/user" endpoint

---

pipelines/resources/deploy-ztp-spokes.yaml

Let's deploy the base infrastructure before we do the final mirror and disconnect. This means will be
pulling from the HUB all the images and content needed for these steps.
- Versions: 4.10.9 / 2.4 / 4.9
- Hardware: real hardware

Moving the ui and workers steps earlier in the pipeline

---

deploy-ui/manifests/deployment.yaml
ui/backend/src/endpoints/user.ts
ui/backend/src/index.ts
ui/backend/src/k8s/oauth.ts
ui/backend/src/k8s/utils.ts
ui/scripts/deployment.yaml

No functional change should be present, just replacing recent approach by more generic one.

Compose CLUSTER API URL from env variables

---

deploy-ui/deploy.sh
deploy-ui/manifests/clusterrolbinding.yaml

To be allowed to create tokenreviews to query token's username.

MGMT-10254 Add clusterrolebinding to UI's default service account

---

documentation/ztp-for-factories/ztp-for-factory-pipeline-edge.adoc
documentation/ztp-for-factories/ztp-for-factory-pipeline-hub.adoc

This PR fixes small typos in the documentation section
Fixes #238 

Fixing small typos

---

ui/frontend/src/components/DomainPage/__snapshots__/DomainSelector.test.tsx.snap
ui/frontend/src/components/UsernamePage/__snapshots__/UsernameSelector.test.tsx.snap
ui/frontend/src/components/utils.test.ts
ui/frontend/src/components/utils.ts

and can not be used for the new account.

MGMT-10296 Kubeadmin username is reserved

---

contrib/gpu-operator/deploy.sh
contrib/gpu-operator/manifests/03-gpu-subscription.yaml
contrib/gpu-operator/verify.sh
deploy-spoke/configure_disconnected.sh
pipelines/resources/deploy-ztp-spokes.yaml

Fix add gpu operator

---

hack/set-motd/main.go
hack/set-motd/main_test.go

Adding some tests to set-motd just for fun and learning purposes.
This change introduces tests.

Add tests to set-motd

---

ui/backend/src/common/resources/clusteroperator.ts
ui/backend/src/common/resources/index.ts
ui/backend/src/common/resources/pod.ts
ui/backend/src/common/resources/statuscondition.ts
ui/backend/src/k8s/oauth.ts
ui/frontend/src/App.tsx
ui/frontend/src/components/PersistPage/PersistPageBottom.css
ui/frontend/src/components/PersistPage/PersistPageBottom.tsx
ui/frontend/src/components/PersistPage/__snapshots__/PersistPage.test.tsx.snap
ui/frontend/src/components/PersistPage/constants.ts
ui/frontend/src/components/PersistPage/persist.ts
ui/frontend/src/components/PersistPage/persistDomain.ts
ui/frontend/src/components/PersistPage/persistIdentityProvider.ts
ui/frontend/src/components/PersistPage/persistServices.ts
ui/frontend/src/components/PersistPage/utils.ts
ui/frontend/src/components/PersistProgress/PersistProgress.tsx
ui/frontend/src/components/PersistProgress/index.ts
ui/frontend/src/components/Settings/SettingsPageRight.css
ui/frontend/src/components/Settings/SettingsPageRight.tsx
ui/frontend/src/components/Settings/__snapshots__/Settings.test.tsx.snap
ui/frontend/src/components/utils.ts
ui/frontend/src/resources/clusteroperator.ts
ui/frontend/src/resources/resource-request.ts

MGMT-10009 Add monitoring of operators before UI redirect

---

hack/deploy-hub-local/ansible/tasks/services/chronyd/00-chrony-base.yaml

Add ignore_errors when chronyd is not capable of force sync

Add ignore_errors

---

.github/workflows/testing-pr.yml

feat(ci): set/unset motd when a worker start or finishes being used by CI

---

finish-deployment/deploy.sh

This is an addition of # in a bash file, just for testing purposes.

Harmless change to trigger an event pull_request

---

finish-deployment/deploy.sh

This PR fixes the path of SA ztpfw-csr-approver in the kubeconfig creation step.

fix(deploy): fix csr-autoapprover serviceaccount path

---

.github/workflows/testing-pr.yml

Fix the variables set to set-motd -motd $VARS by creating the string first in a comprehensive way so bash can interpret it correctly.

fix(ci): fix set-motd variables

---

.github/workflows/testing-pr.yml

Reduce verbosity of set-motd by not including the PR body.

fix(ci): reduce set-motd verbose

---

hack/deploy-hub-local/ansible/tasks/files/bashrc

Add some help messages for set-motd at root login time.

feat(ansible): add set-motd help in bashrc

---

.github/workflows/testing-pr.yml

Task name is a bit confusing because it mentions VM creation, but in reality, is the full pipeline execution (so it takes time...)

Adjust task name

---

hack/deploy-hub-local/ansible/tasks/base/02-bin-utils.yaml

Fixes a "]" that should't be in the motd.

fix(ansible): small motd fix

---

hack/deploy-hub-local/ansible/tasks/base/02-bin-utils.yaml

fix(ansible): current duplicated word

---

pipelines/bootstrap.sh
pipelines/manifests/02-tektonconfig.yaml

This CR seems to be required now as newer hub deployments are failing because of missing CRs
that are created based on the definition of the TektonConfig
- Versions:
- Hardware:

Add tektonconfig definition

---

hack/deploy-hub-local/ansible/tasks/files/bashrc

Control the hub and edge function exist statuses properly.

fix(ansible): control hub and edge function errors properly

---

deploy-disconnected-registry/deploy.sh

cephfs does not support selinux option, but the default Kubernetes mechanism is to instruct the underlying container runtime (crio on this case) to relabel all the files under a given volume.
In SELinux enabled systems this results in bugs [1] under certain conditions like high number of files, where the selinux labeling can't keep up and fails.
In our case scenario, the errors starts when the tekton pipeline runs the olm mirror, which tries to create thousand of files (blobs, metadata, etc) to mirror the release into the edge cluster quay registry, backed by cephfs.
At some point, the mirror stops working because the quay-database (postgresql) and clair-database (postgresql) backing filesystems can't be labeled anymore, making these pods enter CrashLoopBackoff.
An extract of the "oc adm …

fix(registry): selinux patch to handle BZ#2033639

---

hack/deploy-hub-local/ansible/tasks/files/bashrc

Add minor tweaks:
- prompt will show hub cluster as red when logged in
- proper error messages 

feat(ansible): add some minor tweak to bashrc

---

.github/workflows/ui.yml

Adapting the UI tests to the new workflow, so we have a way to skip or force-test these.

feat(ci): adapt ui ci to new workflow

---

hack/deploy-hub-local/ansible/tasks/base/01-packages.yaml
hack/deploy-hub-local/ansible/tasks/services/sshd/00-mosh-base.yaml

build: Enable mosh

---

deploy-odf/manifests/04-ODF-StorageCluster.yaml

Restore replicas to 3 for testing

fix(ODF): Set back replicas to 3 because of lack of stability

---

.github/workflows/needs-rebase.yaml

Label PR's that require a rebase before evaluation

ci(needsrebase): Add CI for testing if PR needs rebase

---

ui/frontend/src/components/ApiAddressPage/ApiAddressPage.tsx
ui/frontend/src/components/IngressIpPage/IngressIpPage.tsx
ui/frontend/src/components/K8SStateContext.tsx
ui/frontend/src/components/WelcomePage/initialDataLoad.ts
ui/frontend/src/components/utils.ts

A validation error is shown when the user enters the same IP for both Ingress and API.
- Versions:
- Hardware:

MGMT-10593 Prevent using the same IP address for both Ingress and API

---

ui/frontend/src/components/PersistPage/constants.ts
ui/frontend/src/components/Settings/DeleteKubeadminButton.tsx

When the kubeadmin account is deleted, the user is notified about the
result.
- Versions:
- Hardware:

MGMT-10549 Inform about success after kubeadmin removal

---

deploy-metallb/manifests/04-NMS-Operand.yaml
deploy-metallb/manifests/nncp.yaml
deploy-odf/manifests/04-ODF-StorageCluster.yaml
finish-deployment/manifests/nmstate.yaml
finish-deployment/manifests/nncp.yaml

Use nmstate/v1 instead of v1beta1, since the features we use are in v1 completely and v1beta1 will be removed in future releases.
Fixes MGMT-10369 [(issue)](https://issues.redhat.com/browse/MGMT-10369)

fix(metallb): update nmstate api to v1

---

.github/workflows/ui.yml

Attempt to listen also  on label events to run CI when  needed

ci(ui): check also on labelling so that CI is executed

---

.github/labels.yml

Add test-ci-ui label when we're touching files under ui/

ci(labels.yaml): add labels to test-ui-ci when touching code there

---

.github/labels.yml
.github/workflows/ci-test-ansible.yml
hack/deploy-hub-local/ansible/inventory-ci

This change includes:
- ansible-playbook runs setup.yaml against one fixed vm
- mock inventory and automated process
- auto label of PR's modifying the ansible path:
- tag the proper component
- force the correct test

ci(ansible): add ansible battery test

---

.github/workflows/testing-pr.yml

Adds or removes 'ok-to-merge' from PR's based on CI status
Fixes #322

ci(testing-pr): Autoadd/remove label 'ok-to-merge' based on test status

---

ui/frontend/src/components/UsernamePage/UsernameSelector.tsx
ui/frontend/src/components/UsernamePage/__snapshots__/UsernamePage.test.tsx.snap
ui/frontend/src/components/UsernamePage/__snapshots__/UsernameSelector.test.tsx.snap

MGMT-10554 Rephrase the UsernamePage

---

.github/labels.yml
.github/workflows/ci-test-ansible.yml
.gitleaks.toml
hack/deploy-hub-local/ansible/inventory-ci
hack/deploy-hub-local/ansible/tasks/base/00-base-os.yaml

Fine tunning of the ansible workflow so it does not fail in:
- galaxy modules
- infosec false positive
- running the playbook against the correct ip
- cleaning the work done before and after

ci(ansible): fine-tunning the ansible workflow

---

.github/workflows/jekyll.yml

Build docs only on docs changes

ci(jekyll): build website only on doc changes

---

.github/workflows/ui.yml

Filter paths so that only UI.yaml is executed when there are UI changes

ci(ui.yaml): run UI ci only when there are commits for it

---

.github/workflows/ui.yml

Use actions-cache to speed up yarn dependency setup

ci(ui.yaml): attempt to add yarn to cache to speed up builds

---

images/Containerfile.pipeline

Adds netcat to test SNO DNS connectivity

fix(Containerfile): add netcat for SNO DNS testing and workaround

---

.github/labels.yml
hack/deploy-hub-local/ansible/inventory-ci

Proper nameserver for ansible ci environment.

ci(ansible): proper nameservers for ansible-ci vm´s

---

.github/workflows/testing-pr.yml
.github/workflows/ui.yml

Always test UI and image creation for each PR as this is usually really fast and shouldn't be hard blocker of full testing

ci(ui): always test and build UI unless skip tags used

---

ui/frontend/src/components/utils.ts

MGMT-10594 Ease rules for IPv4 validation

---

ui/frontend/src/components/DomainPage/DomainSelector.tsx
ui/frontend/src/components/DomainPage/__snapshots__/DomainPage.test.tsx.snap
ui/frontend/src/components/DomainPage/__snapshots__/DomainSelector.test.tsx.snap

We are positioning the `Optional` badge differently on the Domain Page.
- Versions:
- Hardware:

MGMT-10183 Move "Optional" badge on the Domain Page

---

.github/workflows/testing-pr.yml
pipelines/bootstrap.sh
shared-utils/verify_preflight.sh

Revisit labeler as currently lacks permissions to add the labels to the pr's that have CI passing  (pull_request vs pull_request_target)

ci(labeler): disable labeler as it's lacking currently permissions

---

.github/workflows/size.yaml

Adds size label based on pr changes

ci(size): Add size label for the code change

---

.github/workflows/broken-link-check.yml

- Add manual trigger to the broken links action
- ignore docs.github.com

ci(broken-link): ignore docs.github.com

---

.github/workflows/broken-link-check.yml

This should be the format used by gh actions to represent arrays, since it's yaml.

ci(broken-link): gihub actions array format

---

.github/workflows/broken-link-check.yml

Instead of setting envvars, use with to pass the variable as input to the action.
Can't be tested in other branch, only in main.

ci(broken-link): use with instead of env

---

hack/deploy-hub-local/ansible/tasks/base/01-packages.yaml

Add fpaste as common package installed by ansible.
Fixes # [(issue)](https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/issues/385)
N/A

ansible(packages): add fpaste as common pkg

---

deploy-disconnected-registry/common.sh
shared-utils/common.sh

The certificate of  registry is added to the host trust in the prior steps but never gets added to OpenShift itself
Fixes #382 
Fixes #383

fix(registry): Add certificate to OpenShift objects to be able to pull after ICSP

---

pipelines/bootstrap.sh

Signed-off-by: eifrach <eifrach@redhat.com>
* adding option to run a local copy of `bootstrap.sh`  
Fixes #282 
- Versions:
- Hardware:

Adding option to run bootstrap with local copy

---

contrib/gpu-operator/deploy.sh
contrib/gpu-operator/manifests/03-gpu-subscription.yaml

No need to pass this data. If ommited, OLM will pick the latest available
- Versions:
- Hardware:

Don't pass the starting CSV version

---

deploy-hub-configs/deploy.sh

Speaking with Mario, mentioned that this should no longer be needed, removing

fix(hub-config/deploy): Remove obsolete Hive patch

---

pipelines/bootstrap.sh

The BRANCH variable is used the clone_ztp
function.
- Versions:
- Hardware:

Need to export BRANCH earlier

---

.github/workflows/build-and-push-release.yml

Clean old resources used by podman:
- Maximum 3 weeks old
- Delete containers and images
Fixes #404 
[ ] Change has to be tested in main

ci(housekeeping): clean old container resources

---

.github/workflows/testing-pr.yml

Adding bootstrap to CI procedure 

Ci Bootstrap before pipeline

---

ui/backend/package.json
ui/backend/yarn.lock
ui/frontend/package.json
ui/frontend/yarn.lock

Currently the latest versions of both.

UI: Update react-scripts 5.0.1 and eslint to 8.18.0

---

.github/workflows/testing-pr.yml

Signed-off-by: eifrach <eifrach@redhat.com>
enabling UI failure on build

re-enabling UI testing

---

ui/frontend/src/components/PersistPage/PersistPageBottom.tsx
ui/frontend/src/components/PersistPage/__snapshots__/PersistPage.test.tsx.snap

Message
```
Please keep this window open until the process is finished.
```
is rendered sooner

[UI] Be more talkative for the user waiting for data to be persisted

---

ui/frontend/package.json
ui/frontend/src/components/PersistPage/__snapshots__/PersistPage.test.tsx.snap
ui/frontend/src/setupTests.ts
ui/frontend/yarn.lock

[UI] Fix unit tests

---

.github/labels.yml

ci(labels): label al UI pr's to perform test-ci-ui automatically

---

deploy-edgecluster/render_edgeclusters.sh
images/Containerfile.pipeline

Revert signatures workaround once that BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2073197#c19 has been fixed and released
Fixes #354

revert: Revert signatures workaround

---

ui/frontend/src/components/PersistPage/persist.ts
ui/frontend/src/components/PersistPage/persistDomain.ts
ui/frontend/src/components/PersistPage/persistIdentityProvider.ts
ui/frontend/src/components/PersistPage/persistServices.ts
ui/frontend/src/components/PersistPage/utils.ts
ui/frontend/src/components/PersistProgress/PersistProgress.tsx

Every step transition is blocked on having reconciliation done.
TODO:

MGMT-10897 Make the persistence synchronous

---

images/Containerfile.UI
ui/package.json

Attempt to solve SIGSEGV of "yarn lint" executed in a container.

[UI] Update yarn and run tests synchronously

---

ui/frontend/src/components/PersistPage/persist.ts

[UI] Unregister OnUnloadPage handler sooner

---

Makefile
hack/deploy-hub-local/build-edgecluster.sh
hack/deploy-hub-local/create-vm.yml

feat: Upgrade to ODF 4.10

---

.github/workflows/ui.yml
images/Containerfile.UI
ui/frontend/package.json
ui/frontend/yarn.lock
ui/package.json
ui/yarn.lock

In an attempt to fix SIGSEGV of eslint in the CI

[UI] Split frontend/backend test/build steps

---

hack/deploy-hub-local/ansible/inventory-ci

ci(ansible): define virt-host profile for hosts

---

deploy-edgecluster/render_edgeclusters.sh

…otation
- Versions:
- Hardware:

MGMT10771-single nic sdn removing double route

---

deploy-metallb/deploy.sh

fix the bug for metallb operator
Backport for the metallb fix! This will be removed later on but it's currently needed for the metallb deployment to succeed.
More info here: https://github.com/openshift/kubernetes-nmstate/pull/287
- Versions:
- Hardware:

Backport for PR #469 (metallb workaround for their service account)

---

deploy-edgecluster/render_edgeclusters.sh

Backport:
* change with sdn and remove double route forcing openshiftsdn with annotation
* fix issue removing sdn  to use override
(cherry picked from commit 5d89df556c85e49085627267e9d593d8d0f9181c)

MGMT10771-single nic sdn removing double route (#470)

---

deploy-metallb/deploy.sh

Backprot for Bug 2106840: metallb order patch #476

Bug 2106840: metallb order patch #476

---

Makefile

Reverts rh-ecosystem-edge/ztp-pipeline-relocatable#478

Revert "Fix: Makefile issue with release tag"

---

Makefile

Backport for multiple optimizations to the Makefile

Makefile backports

---

finish-deployment/deploy.sh

A small mispell is corrected.
- Versions:
- Hardware:

Correcting a mispell.

---

deploy-metallb/deploy.sh

The bug 2106840 was verified. Removing the workaround
associated with the issue.
- Versions:
- Hardware:

NO_ISSUE: Removing a workaround for a verified bug.

---

.github/workflows/testing-pr-compact.yml
.github/workflows/testing-pr-sno.yml

add new pipline to test manual with label sno and compact, removing the approve
The idea about testing ci PR will be:
- New labels will be created: "test-sno" "test-compact" and will be removed the current "test-ci" 
- PR owner is responsible to pass at least 1 test using "test-sno" and/or "test-compact" for each PR depending of the feature to be merged.
- We MUST showing the result in the PR description as a warranty of success for the rest of PR reviewers. If there's a test we cannot merge the PR to ensure every PR is tested.
- No automated test will be launched with the approval
- If you need add more commits in the PR but you don't want to pass new tests, you need to remove the label before if you don't want …

NO_ISSUE: add new pipeline to test manual with label sno and compact

---

.github/workflows/testing-pr-compact.yml
.github/workflows/testing-pr-sno.yml
.github/workflows/testing-pr.yml
deploy-metallb/deploy.sh
deploy-odf/deploy.sh
deploy-odf/verify.sh
finish-deployment/deploy.sh
hack/deploy-hub-local/create-vm.yml
ui/README.md

ff registry 

---

Makefile
deploy-disconnected-registry/common.sh
deploy-lvmo/deploy.sh
deploy-lvmo/manifests/01-Namespace.yaml
deploy-lvmo/manifests/02-LVMO-OperatorGroup.yaml
deploy-lvmo/manifests/03-LVMO-Subscription.yaml
deploy-lvmo/manifests/04-LVMO-LVMOCluster.yaml
deploy-lvmo/verify.sh
pipelines/resources/deploy-ztp-edgeclusters-sno.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-lvmo.yaml
pipelines/resources/edgeclusters/kustomization.yaml

Add a deploy-lvmo component
The LVMO component is part of the main repo as it is used for all the edgecluster, SNO, deployments. LVMO will serve as the base storage layer for SNO and other components like Quay.
Pipeline run:
openshift-storage pods:
LVMCluster:
Bound PVC with test pod (block):
Bound PVC with test pod (file):
- Versions:
- Hardware:

MGMT-11303: Add a deploy-lvmo component

---

ui/frontend/yarn.lock

UI: Update browserslist to latest

---

ui/frontend/src/components/Settings/SettingsPageRight.css
ui/frontend/src/components/Settings/SettingsPageRight.tsx

MGMT-10982: Fix Save button position for custom certificates

---

deploy-disconnected-registry/common.sh
deploy-odf/manifests/02-ODF-OperatorGroup.yaml
deploy-odf/manifests/03-ODF-Subscription.yaml

We have been installing just the OCS operator since that's all we needed. As part of the ODF on SNO work, we need to be able to install other operators that are under the ODF umbrella. To that end, we need to make sure that the ODF operator ins installed.
No other change is needed as the ODF operator will automatically create the `StorageSystem` CR and install the required operators once the `StorageCluster` is created.
Only tested on compact. The ODF integration for SNO will come in a separate PR
Manual testing on `flavio6`
LSO and ODF steps succeeding:
StorageCluster created:
OCS components installed in the edgecluster:
ODF components installed in the edgecluster
StorageClass list (note that the rbd one is the default):
- …

MGMT-11305: Install the ODF operator instead of OCS

---

ui/backend/src/common/types.ts
ui/backend/src/endpoints/configure.ts
ui/backend/src/endpoints/index.ts
ui/backend/src/endpoints/readiness.ts
ui/backend/src/endpoints/validateDomain.ts
ui/backend/src/index.ts
ui/frontend/src/components/DomainPage/DomainPage.tsx
ui/frontend/src/components/DomainPage/validateDomain.ts
ui/frontend/src/components/K8SStateContext.tsx
ui/frontend/src/components/Settings/SettingsPageRight.tsx
ui/frontend/src/components/WizardFooter/WizardFooter.tsx
ui/frontend/src/components/types.ts

Provided new cluster domain name is resolved before transitioning to
another wizard's page.

MGMT-10712: Validate domain name resolution

---

deploy-odf/deploy.sh
deploy-odf/manifests/04-MCG-StorageCluster.yaml
pipelines/resources/deploy-ztp-edgeclusters-sno.yaml

Install ODF in the SNO cluster. This PR enables the following:
- ODF operator
- Noobaa operator
It configures both of them to create the required storage for the upcoming PR that will add quay to the SNO edgecluster
Pipeline tasks:
Storage class edgecluster:
pods in edgecluster's openshift-storage namespace: (note the nooba containers)
Noobaa and storage system in the edgecluster:
- Versions:
- Hardware:

MGMT-11015: Install ODF for SNO edgecluster

---

hack/deploy-hub-local/lab-nfs.sh

Reduce max number of PV's to lower storage barrier

ci: reduce number of pv's to lower storage requirements

---

pipelines/resources/deploy-ztp-edgeclusters-sno.yaml

Login and push to edgecluster registry:
Registry pods on the edge cluster: 
PVs:
Nodes:
Pipelinerun:
- Versions:
- Hardware:

MGMT-11380: Deploy Quay in SNO clusters

---

ui/frontend/src/components/DomainCertificatesPage/DomainCertificatesPanel.tsx

MGMT-11366: Fix wording for custom certificates

---

ui/frontend/src/components/Settings/SettingsPageRight.tsx

MGMT-10788: Use Retry for button name in case of error

---

deploy-odf/deploy.sh

There was a missing `grep master` in the master count command
- Versions:
- Hardware:

NO_ISSUE: make sure we are counting only masters

---

images/Containerfile.UI

UI Image: add bind-utils

---

ui/frontend/src/components/DomainPage/DomainSelector.tsx
ui/frontend/src/components/DomainPage/__snapshots__/DomainPage.test.tsx.snap
ui/frontend/src/components/DomainPage/__snapshots__/DomainSelector.test.tsx.snap

MGMT-10891: Rephrase Custom Domain page

---

ui/frontend/src/components/DomainCertificatesDecisionPage/DomainCertificatesDecision.tsx
ui/frontend/src/components/DomainCertificatesPage/DomainCertificatesPanel.tsx
ui/frontend/src/components/K8SStateContext.tsx
ui/frontend/src/components/Settings/SettingsPageDomainCertificates.tsx
ui/frontend/src/components/Settings/SettingsPageRight.tsx
ui/frontend/src/components/types.ts

Changes:
- emphasizing information about self-generating certificate when not provided
- requiring at least one custom cert when Manual option is selected
- clearing manually added certificates when the user switches back to Automatic

MGMT-10846: Emphasize auto-generating of certs when not provided

---

deploy-odf/deploy.sh
pipelines/resources/deploy-ztp-edgeclusters-sno.yaml

PipelineRun describe: 
Podman Login and pull from edgecluster:
- Versions:
- Hardware:

MGMT-11381: Enable image mirroring for SNO

---

.gitignore
hack/deploy-hub-local/build-edgecluster.sh
hack/deploy-hub-local/build-hub.sh

Signed-off-by: root <root@flavio1.alklabs.local>
1. changing YAML configuration files to `edgecluster.yaml`
2. adding custom registry to YAML config
```console
$ cat hack/deploy-hub-local/edgecluster.yaml
config:
OC_OCP_VERSION: '4.10.20'
OC_ACM_VERSION: '2.5'
OC_ODF_VERSION: '4.10'
REGISTRY: flavio4.alklabs.local:5000
edgeclusters:
```

fixing deploy hub, adding registry option

---

pipelines/resources/deploy-ztp-hub-mce.yaml
pipelines/resources/deploy-ztp-hub.yaml
pipelines/resources/hub/hub-deploy-acm.yaml
pipelines/resources/hub/hub-deploy-disconnected-registry.yaml
pipelines/resources/hub/hub-deploy-httpd-server.yaml
pipelines/resources/hub/hub-deploy-hub-config.yaml
pipelines/resources/hub/hub-deploy-icsp.yaml
pipelines/resources/hub/hub-deploy-mce.yaml
pipelines/resources/hub/hub-save-config.yaml

NO_ISSUE: Set workspace for hub pipelines too

---

hack/deploy-hub-local/ansible/tasks/files/bashrc

Overwrite kubeconfig on edge command for CI

NO_ISSUE: Overwrite kubeconfig on extract

---

documentation/ztp-for-factories/ztp-configuring-edge-at-remote-site.adoc

Per https://issues.redhat.com/browse/MGMT-11333
- Versions:
- Hardware:

Adjusting the doc.

---

deploy-disconnected-registry/olm-sync.sh

Tested on a fresh hub deployment
- Versions:
- Hardware:

NO_ISSUE: Remove hardcoded workspace path, use OUTPUTDIR

---

documentation/ztp-for-factories/ztpfw-pipelines-flags-arguments.adoc

The longer the message - the more room for confusion.
- Versions:
- Hardware:

Shortening a long param message

---

documentation/ztp-for-factories/ztp-configuring-edge-at-remote-site.adoc

The previous note was a bit raw.
- Versions:
- Hardware:

Rephrasing a note.

---

documentation/ztp-for-factories/ztp-configuring-edge-at-remote-site.adoc

Improving the message for SSH key download.

---

documentation/ztp-for-factories/ztp-configuring-edge-at-remote-site.adoc

The message in UI got changed. Updating the doc.
- Versions:
- Hardware:

Updating the doc per update in UI.

---

documentation/ztp-for-factories/ztpfw-pipelines-flags-arguments.adoc

Adding a command how to get the list of params.
- Versions:
- Hardware:

List of params.

---

documentation/ztp-for-factories/ztpfw-pipelines-flags-arguments.adoc

Per https://issues.redhat.com/browse/MGMT-11483
- Versions:
- Hardware:

Several fixes to arguments in table.

---

documentation/ztp-for-factories/ztp-configuring-edge-at-remote-site.adoc

Some info was missing from the doc.
- Versions:
- Hardware:

Setup complete addition.

---

documentation/ztp-for-factories/ztp-configuring-edge-at-remote-site.adoc

It differs a bit.
- Versions:
- Hardware:

Additional words for changing domain flow

---

documentation/ztp-for-factories/ztp-configuring-edge-at-remote-site.adoc

More documentation data
- Versions:
- Hardware:

certificates screens

---

hack/deploy-hub-local/create-vm.yml

Signed-off-by: Eran Ifrach <eifrach@redhat.com>
increasing Disk size due to some overhead on mirror

changing disk size

---

deploy-lvmo/deploy.sh

NO_ISSUE: Adding the missing function.

---

ui/frontend/src/components/Settings/SettingsPageRight.tsx

MGMT-10788: Keep Retry button forever since first error

---

ui/frontend/src/components/DownloadSshKeyPage/DownloadSshKey.tsx

MGMT-11641: Rephrase for failed SSH key download

---

ui/frontend/src/components/DomainCertificatesPage/DomainCertificatesPanel.tsx

MGMT-11488: Split a sentence on the custom certs page

---

ui/frontend/src/components/DownloadSshKeyPage/DownloadSshKey.tsx

MGMT-11641: Show error message for SSH key download

---

documentation/ztp-for-factories/ztp-configuring-edge-at-remote-site.adoc

Completing the section and mentioning the
kubeadmin deletion.
- Versions:
- Hardware:

Updates to completing the setup.

---

documentation/ztp-for-factories/ztp-for-factory-overview-ocp-docs.adoc

Issues #https://issues.redhat.com/browse/MGMT-11201
- Versions:
- Hardware:

Clarifying on supported scenarios.

---

documentation/ztp-for-factories/ztp-for-factory-prerequisites.adoc

update doc for lvmo in order to create pv dynamically
Fixes # NO-ISSUE
- Versions:
- Hardware:

document the task to deploy lvmo

---

images/Containerfile.pipeline

Waiting for @achuzhoy to test this in his pipeline.
According to 
- Versions:
- Hardware:

MGMT-11935: Move pipeline image to ubi8 to stay closer to downstream builds

---

deploy-edgecluster/render_edgeclusters.sh
documentation/ztp-for-factories/ztp-for-factory-prerequisites.adoc
hack/deploy-hub-local/build-edgecluster.sh
hack/deploy-hub-local/build-hub.sh
hack/deploy-hub-local/create-vm-sno.yml
hack/deploy-hub-local/create-vm.yml
hack/deploy-hub-local/hub-install.yml
shared-utils/verify_preflight.sh

This PR enables the TPMv2 feature for hub and edgecluster in order to have the disks encripted
- Hub requirement (virtualized environment):
- Install ```swtpm``` package in the hypervisor (`yum install -y swtpm`)
- Libvirt configuration: 
device section:
```
<tpm model='tpm-tis'>
<backend type='emulator' version='2.0'/>
</tpm>
```
_The doc section has been updated to explain this in requirements section_
Basically, with the requirement the PR will install tpm and use it for the hub and edgeclusters   
Fixes # [MGMT-11763](https://issues.redhat.com/browse/MGMT-11763)
**HUB tests:**
**Edgecluster tests:**
- Versions: 4.10.20 and 4.10.30
- Hardware: …

MGMT-11763-enable TPMv2

---

documentation/ztp-for-factories/ztp-for-factory-prerequisites.adoc

The doc needs more clarity - we need to have
a manual PVC created and bound or underlying block devices
- Versions:
- Hardware:

Adding pvc and block device notes.

---

deploy-disconnected-registry/deploy.sh
deploy-disconnected-registry/verify.sh

fix the issue with configmap due to base64 -w0
- Versions:
- Hardware:

Fix issue configmap

---

deploy-disconnected-registry/common.sh
deploy-disconnected-registry/update-global-pullsecret.sh
deploy-edgecluster/configure_disconnected.sh

Fix the issue with the route and the pull secret step waiting for a route which doesn't exist.
Fix also, some typo with quotes making the PS step imposible to finish
Fixes # [MGMT-12076](https://issues.redhat.com/browse/MGMT-12076)
- Versions:
- Hardware:

MGMT-12076 fix the issue with timeout to get route in common.sh

---

Makefile
images/Containerfile.UI
ui/frontend/src/components/DownloadSshKeyPage/__snapshots__/DownloadSshKeyPage.test.tsx.snap

(cherry picked from commit 6411accfb9d66356111534614bc0da770d4106c7)

Fix conatiner UI image build (#577)

---

documentation/ztp-for-factories/main.adoc
documentation/ztp-for-factories/ztp-install-factory-edge-pipeline.adoc

The pre-requisites page was not included in the main page with the index.
Local docs genreation
```
ztp-pipeline-relocatable on  main [$!?] via 🐍 v2.7.18 
✦ ✗ grep -r LVMO website
website/1.0/ZTP-for-factories.html:<p>In case you want to use dynamic PV and PVC creation using LVMO - we&#8217;ve prepared a Tekton task to do that:</p>
```
- Versions:
- Hardware:

Add prereq page to docs index

---

pipelines/resources/deploy-ztp-edgeclusters-connected.yaml
pipelines/resources/kustomization.yaml

This pipeline excludes syncing data for the edgeclusters. It will help with execution times/bandwidth/space
- Versions:
- Hardware:

Adding a minimal edgeclusters pipeline

---

documentation/ztp-for-factories/ztp-edge-factory-pipeline.adoc

After this pipeline run is completed, the edge clusters are ready to be shipped to the end customer’s remote site.
- Versions:
- Hardware:

Updated the doc with a more suitable message.

---

documentation/ztp-for-factories/ztp-configuring-edge-at-remote-site.adoc

A repeating word is changed for better readability.
- Versions:
- Hardware:

Small enhancement to the doc

---

documentation/ztp-for-factories/ztp-install-factory-edge-pipeline.adoc
documentation/ztp-for-factories/ztp-install-factory-pipeline.adoc

'Follow the steps in this section'
- Versions:
- Hardware:

Rephrasing a sentence to avoid having the same verb

---

documentation/ztp-for-factories/ztp-for-factory-edgeclusters-yaml.adoc
documentation/ztp-for-factories/ztp-install-factory-edge-pipeline.adoc
documentation/ztp-for-factories/ztp-install-factory-pipeline.adoc
documentation/ztp-for-factories/ztp-post-install-hub-factory-pipeline-checks.adoc
documentation/ztp-for-factories/ztp-pre-hub-install-factory-pipeline-checks.adoc
documentation/ztp-for-factories/ztp-troubleshooting-factory-pipelines.adoc

Updating the version of OCP/OCS
and fixing the path to storage disks set in edgecluster.yaml
- Versions:
- Hardware:

Updating the versions.

---

deploy-disconnected-registry/manifests/pvc-registry.yaml
deploy-disconnected-registry/olm-sync.sh
deploy-edgecluster/render_edgeclusters.sh
documentation/ztp-for-factories/ztp-install-factory-edge-pipeline.adoc
hack/deploy-hub-local/build-edgecluster.sh
hack/deploy-hub-local/build-hub.sh
hack/deploy-hub-local/create-vm-sno.yml
hack/deploy-hub-local/create-vm.yml
pipelines/resources/edgeclusters/edgecluster-deploy-disconnected-registry-edgeclusters-ocp.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-disconnected-registry-edgeclusters-olm.yaml
pipelines/resources/hub/hub-deploy-disconnected-registry.yaml

This PR adds the ability to configure TPM through the `edgeclusters.yaml` file. In addition, it pulls in some changes that @eifrach worked on and it adds a new `config` key, per cluster configuration, to the edgeclusters.yaml that should allow for setting clusterwide configurations.
- Versions:
- Hardware:

MGMT-12602: Allow to configure TPM through edgeclusters.yaml

---

deploy-edgecluster/deploy.sh
deploy-edgecluster/verify.sh
shared-utils/verify_preflight.sh

Small improvements to enable the hub to deploy multiple versions of OCP.
This PR also creates the edgecluster ssh key in the hub earlier in the flow to allow for debugging the cluster in case the agent fails to start.

Small improvements

---

pipelines/resources/deploy-ztp-edgeclusters-sno-connected.yaml
pipelines/resources/kustomization.yaml

The pipeline doesn't have the mirror steps.
- Versions:
- Hardware:

Connected pipeline to deploy SNO edge cluster.

---

Makefile

Per subject.
- Versions:
- Hardware:

Updating the OCP version to 4.10.42

---

documentation/ztp-for-factories/ztp-install-factory-edge-pipeline.adoc

The mandatory entry was missing on some nodes.
- Versions:
- Hardware:

Adding root_disk in examples.

---

documentation/ztp-for-factories/ztp-for-factory-edgeclusters-yaml.adoc
examples/config.yaml

The doc is built from several files.
Updating other locations with examples.
- Versions:
- Hardware:

More changes related to root_disk.

---

documentation/ztp-for-factories/ztp-configuring-edge-at-remote-site.adoc

Per https://issues.redhat.com/browse/MGMT-11357.
- Versions:
- Hardware:

Updating the doc to remove obscurity.

---

documentation/ztp-for-factories/ztp-common-expected-errors.adoc

Just re-organizing the sentences.
- Versions:
- Hardware:

Rephrasing text.

---

pipelines/resources/kustomization.yaml

Updating kustomize to remove old pipeline

---

hack/deploy-hub-local/create-vm-sno.yml
hack/deploy-hub-local/create-vm.yml
hack/deploy-hub-local/hub-install.yml

Actually set the value of tpm param

---

documentation/ztp-for-factories/ztp-edge-factory-pipeline.adoc

We add a single worker, not workers.
- Versions:
- Hardware:

Single worker

---

documentation/ztp-for-factories/ztp-install-factory-edge-pipeline.adoc
documentation/ztp-for-factories/ztp-install-factory-pipeline.adoc
documentation/ztp-for-factories/ztp-post-install-hub-factory-pipeline-checks.adoc
documentation/ztp-for-factories/ztp-troubleshooting-factory-pipelines.adoc

per the title
- Versions:
- Hardware:

Updating the ocs to odf in the doc for edgecluster.yaml

---

documentation/ztp-for-factories/ztp-check-install-hub-factory-pipeline.adoc

The edgecluster-deployer project stores the artifacts

---

documentation/ztp-for-factories/ztp-for-factory-overview-ocp-docs.adoc

Deployed cluster isn't enough. The pipelerun need
to complete.
- Versions:
- Hardware:

Condition to ship the edgecluster.

---

documentation/ztp-for-factories/ztp-install-factory-edge-pipeline.adoc
documentation/ztp-for-factories/ztp-install-factory-pipeline.adoc

We mention hub pipeline while it should be edge.
and slightly rewording
- Versions:
- Hardware:

Edge pipeline should be mentioned

---

documentation/ztp-for-factories/ztp-install-openshift-pipelines.adoc

The bootstrap.sh creates several pipelines
- Versions:
- Hardware:

Multiplt pipelines.

---

documentation/ztp-for-factories/ztp-create-factory-hub-cluster.adoc

This makes it clearer that we need one option, not both
- Versions:
- Hardware:

SNO is an alternative to multinode.

---

documentation/ztp-for-factories/ztp-install-factory-pipeline-overview.adoc

Some tasks run in parallel.

---

documentation/ztp-for-factories/ztp-install-openshift-pipelines.adoc

Related to https://issues.redhat.com/browse/MGMT-11241
- Versions:
- Hardware:

Enhancing the doc.

---

Makefile
deploy-disconnected-registry/oc-mirror-config-edgecluster.yaml
deploy-disconnected-registry/oc-mirror-config-hub.yaml
deploy-disconnected-registry/verify_olm_sync.sh
deploy-edgecluster/render_edgeclusters.sh
deploy-hub-configs/deploy.sh
deploy-hub-configs/registryconf.txt
deploy-lvmo/manifests/05-Hub-PVC.yaml
deploy-mce/03-subscription.yml
deploy-metallb/deploy.sh
deploy-metallb/manifests/02-MLB-OperatorGroup.yaml
deploy-metallb/manifests/address_pool.yaml
deploy-metallb/verify.sh
deploy-worker/change_def_route.sh
deploy-worker/render_worker.sh
pipelines/resources/edgeclusters/edgecluster-deploy-disconnected-registry-edgeclusters-ps.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-disconnected-registry-edgeclusters.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-icsp-edgeclusters-post.yaml
pipelines/resources/hub/hub-deploy-hub-config.yaml
pipelines/resources/hub/hub-deploy-update-global-ps.yaml

Migrate to 4.11
Fixes #[MGMT-12539](https://issues.redhat.com/browse/MGMT-12539)

MGMT-12539: Migrate to 4.11

---

.github/workflows/jekyll.yml
.github/workflows/ui.yml

Disable UI build failures

---

documentation/ztp-for-factories/ztp-create-factory-hub-cluster.adoc

Slight correction.
- Versions:
- Hardware:

Adjusting the doc per https://issues.redhat.com/browse/MGMT-11220

---

documentation/ztp-for-factories/ztp-install-factory-hubedge-architecture.adoc

Rewording the nics section.
- Versions:
- Hardware:

Enhancing the architecture section of the doc.

---

.github/workflows/check-cli.yml

Currently we run the CLI tests on Linux, Windows and macOS, but we are about to introduce tests that will require a container engine (docker or podman) and that will not run correctly on Windows or macOS. As we will be supporting only Linux it is best to just not run the tests on Windows or macOS.
None.

NO-ISSUE: Run tests only in Linux

---

ztp/internal/testing/environment.go

Currently the Kubernetes API testing environment doesn't remove the temporary directories that it creates, this patch fixes that.

NO-ISSUE: Remove testing environment temp dirs

---

ztp/internal/testing/environment.go

Currently the testing environment starts a Kubernetes API server but doesn't wait for it to be ready. In some situations this can cause a problem because tests may try to use it when it isn't ready yet, and will fail. This patch changes the environment so that it waits till the API server is ready according to the `readyz` endpoint.

NO-ISSUE: Wait for API server ready before running tests

---

ztp/internal/templating/engine.go
ztp/internal/templating/engine_test.go
ztp/internal/templating/suite_test.go

This patch moves all the templating code to a new `templating` package.

NO-ISSUE: Add templating package

---

ztp/internal/renderer.go
ztp/internal/renderer_test.go
ztp/internal/testing/text.go

This patch adds a new `Renderer` type that knows how to combine templates with data in order to generate Kubernetes API objects.

NO-ISSUE: Add object renderer

---

documentation/ztp-for-factories/ztp-install-factory-pipeline-overview.adoc
documentation/ztp-for-factories/ztp-intro-factory-install.adoc

Changing the wording from a single to multiple pipelines. Rewording the sentences around "in readiness".
- Versions:
- Hardware:

More than one pipeline should be mentioned.

---

ztp/internal/testing/environment/crds/0010_ingresscontroller.yaml
ztp/internal/testing/environment/crds/0020_agentclusterinstall.yaml
ztp/internal/testing/environment/crds/0030_clusterdeployment.yaml
ztp/internal/testing/environment/crds/0040_managedcluster.yaml
ztp/internal/testing/environment/crds/0050_infraenv.yaml
ztp/internal/testing/environment/crds/0060_nmstateconfig.yaml
ztp/internal/testing/environment/crds/0070_baremetalhost.yaml
ztp/internal/testing/environment_crds.go

This patch adds to the testing environment the custom resource definitions that will be needed to run the tests, together with a set of `go:generate` directives to download them.

NO-ISSUE: Add testing env CRDs

---

ztp/internal/config.go
ztp/internal/config_test.go

This patch adds a test that verifies that some typical configuration files can be loaded correctly.

NO-ISSUE: Add config loading test

---

ztp/internal/config_test.go

This patch adds a test to check that loading a cluster with multiple network interfaces works correctly.

NO-ISSUE: Test loading config with multiple NICs

---

documentation/ztp-for-factories/ztp-post-install-edge-factory-pipeline-checks.adoc

Prerequisite to check edge cluster is having the edgecluster.

---

ztp/internal/data.go

This patch adds to the `data.go` file a set of `go:generate` directives that download updated versions of the embedded CRDs.

NO-ISSUE: Add `go:generate` directives to update CRDs

---

documentation/ztp-for-factories/ztp-create-factory-hub-cluster.adoc

Also adding the SNO case - less IPs.
- Versions:
- Hardware:

Correcting the number of minimum required IPs.

---

.github/workflows/check-cli.yml
ztp/go.mod
ztp/go.sum

This patch updates the code and the build scripts to use Go 1.20.

NO-ISSUE: Build with Go 1.20

---

.github/workflows/check-cli.yml
ztp/.containerignore
ztp/Containerfile

This patch adds a `Containerfile` to build the CLI image.

NO-ISSUE: Add Containerfile for CLI

---

deploy-disconnected-registry/oc-mirror-config-hub.yaml

Fixes #[MGMT-13583](https://issues.redhat.com/browse/MGMT-13583)
- Versions:
- Hardware:

MGMT-13583: Update MCE mirrored channels

---

ztp/internal/applier_test.go
ztp/internal/client_test.go
ztp/internal/cmd/create_cluster_cmd_test.go
ztp/internal/config_test.go
ztp/internal/context_test.go
ztp/internal/enricher_test.go
ztp/internal/jq_test.go
ztp/internal/logging/flags.go
ztp/internal/logging/logger.go
ztp/internal/logging/logger_test.go
ztp/internal/logging/transport_wrapper.go
ztp/internal/logging/transport_wrapper_test.go
ztp/internal/templating/engine_test.go
ztp/internal/tool.go
ztp/internal/tool_test.go

This patch adds the `--log-level` and `--log-file` command line options to control the log level and file.

NO-ISSUE: Add --log-level and --log-file options

---

ztp/internal/logging/logger.go
ztp/internal/logging/logger_test.go

Currently the log file is created with execution permissions, which is wrong. This patch fixes that.

NO-ISSUE: Fix permissions of log file

---

ztp/internal/logging/logger_test.go

This patch adds a test to verify that the logger honors the `--log-level` and `--log-file` flags.

NO-ISSUE: Add test for log flags

---

ztp/internal/enricher.go
ztp/internal/enricher_test.go

Currently the enricher always generates new SSH keys, even when the secret containing them already exists. This patch changes it so that it will only create them when really needed.

NO-ISSUE: Don't generate SSH keys if they already exist

---

ztp/go.mod
ztp/go.sum
ztp/internal/applier.go
ztp/internal/applier_listener.go
ztp/internal/applier_listener_test.go

This patch changes the applier listener so that it calculates friendly names for objects converting the camel case names to lists of words.

NO-ISSUE: Improve applier listener

---

deploy-disconnected-registry/oc-mirror-config-edgecluster.yaml
deploy-disconnected-registry/oc-mirror-config-hub.yaml

Mirror OCP release candidates images to allow us to test fixes faster
- Versions:
- Hardware:

Mirror OCP release candidates

---

pipelines/resources/deploy-ztp-edgeclusters-sno.yaml
pipelines/resources/deploy-ztp-hub.yaml

Update task timeout for hub deployment

---

documentation/ztp-for-factories/ztp-for-factory-prerequisites.adoc

Aligning with the following storage requirement later in the doc
- Versions:
- Hardware:

Adjusting storage requirements.

---

ztp/internal/cmd/create/cluster/create_cluster_cmd.go
ztp/internal/cmd/create_cluster_cmd_test.go
ztp/internal/testing/text.go

Currently the CLI doesn't waits for clusters to be installed. This takes a long time and the CLI stays silent. This patch changes it so that it will write a message when there is a change in state.
Tested manually and with the included unit tests.

NO-ISSUE: Report changes of state

---

ztp/internal/cmd/create/cluster/create_cluster_cmd.go

This patch adds to the `create cluster` command an `--output` flag that indicates the directory for output files, in particular SSH keys. This is necessary because the next steps in the pipeline, still shell scripts, need those files.

NO-ISSUE: Add `--output` flag

---

ztp/internal/applier_test.go
ztp/internal/client.go
ztp/internal/cmd/create/cluster/create_cluster_cmd.go
ztp/internal/cmd/create_cluster_cmd_test.go
ztp/internal/cmd/delete/cluster/delete_cluster_cmd.go
ztp/internal/cmd/dev/cleanup/dev_cleanup_cmd.go
ztp/internal/cmd/dev/create/dev_create_cmd.go
ztp/internal/cmd/dev/delete/dev_delete_cmd.go
ztp/internal/cmd/dev/setup/dev_setup_cmd.go
ztp/internal/enricher_test.go
ztp/internal/logging/list.go
ztp/internal/logging/list_test.go

This patch adds support for connecting to the Kubernetes API server via an SSH tunnel.

NO-ISSUE: Add SSH tunnel support

---

ztp/internal/applier_listener.go
ztp/internal/applier_listener_test.go
ztp/internal/cmd/create/cluster/create_cluster_cmd.go
ztp/internal/cmd/delete/cluster/delete_cluster_cmd.go
ztp/internal/cmd/dev/cleanup/dev_cleanup_cmd.go
ztp/internal/cmd/dev/create/dev_create_cmd.go
ztp/internal/cmd/dev/delete/dev_delete_cmd.go
ztp/internal/cmd/dev/setup/dev_setup_cmd.go
ztp/internal/cmd/version/version_cmd.go
ztp/internal/console.go
ztp/internal/console_test.go
ztp/internal/context.go
ztp/internal/context_test.go
ztp/internal/tool.go

This patch adds a new console object that replaces the existing `fmt.Fprintf` calls.

NO-ISSUE: Add console

---

ztp/internal/applier.go
ztp/internal/applier_test.go
ztp/internal/cmd/create/cluster/create_cluster_cmd.go
ztp/internal/cmd/dev/apply/dev_apply_cmd.go
ztp/internal/cmd/dev/delete/dev_delete_cmd.go
ztp/internal/cmd/dev/dev_cmd.go
ztp/internal/cmd/dev/setup/dev_setup_cmd.go
ztp/internal/enricher_test.go

Apply matches better what the method does: it creates the objects if they don't exist, and updates the status.

NO-ISSUE: Rename `applier.Create` to `applier.Apply`

---

ztp/internal/applier.go
ztp/internal/cmd/create/cluster/create_cluster_cmd.go
ztp/internal/cmd/delete/cluster/delete_cluster_cmd.go
ztp/internal/config/loader.go
ztp/internal/config/loader_test.go
ztp/internal/config/suite_test.go
ztp/internal/enricher.go
ztp/internal/jq/suite_test.go
ztp/internal/jq/tool.go
ztp/internal/jq/tool_test.go

This patch moves the code that loads the configuration to a separate package. This will it make it easier to add configuration utilities that can be used from other packages.

NO-ISSUE: Move config code to a separate package

---

shared-utils/common.sh

Currently we only focus on master nodes.
- Versions:
- Hardware:

Select agents only for masters

---

deploy-edgecluster/render_edgeclusters.sh

Don't set the internal IP twice

---

deploy-edgecluster/99-add-host-int-ip.sh

Don't set secondary IP on br-ex if there are 2 interfaces

---

pipelines/resources/deploy-ztp-edgeclusters-connected.yaml
pipelines/resources/deploy-ztp-edgeclusters-sno-connected.yaml
pipelines/resources/deploy-ztp-edgeclusters-sno.yaml
pipelines/resources/deploy-ztp-edgeclusters.yaml

Noticed that it takes less than 4 mins to complete. Setting the timeout to 30 mins to avoid a 6 hours wait. For https://issues.redhat.com/browse/MGMT-12937?filter=12402997
- Versions:
- Hardware:

Setting timeout for metallb.

---

documentation/ztp-for-factories/ztp-create-factory-hub-cluster.adoc

Providing clarity to network requirement related sentence.

---

ztp/internal/applier.go
ztp/internal/applier_test.go

Currently the code that waits for CRD to be created doesn't work correctly because it takes the group and kind from the metadata of the objects in events it receives, which will always be `apiextensions.k8s.io/v1` and `CustomResourceDefinition`. It should instead use the `.spec.group` and `.spec.names.kind` fields of the object. This patch fixes that.

NO-ISSUE: Fix wait for CRD

---

ztp/internal/applier.go

When the creation of an object fails after waiting for the CRD to exist it is frequent to have 500 errors while the webhooks aren't yet available. This patch changes the applier so that it retries when that happens.

NO-ISSUE: Retry when creation fails with 500

---

ztp/internal/applier.go
ztp/internal/config/loader.go
ztp/internal/enricher.go
ztp/internal/jq/tool.go

This patch changes the code so that it wraps errors using `%w` instead of `%v`.

NO-ISSUE: Use %w instead of %v

---

ztp/internal/console.go
ztp/internal/console_test.go

This patch changes the console so that it replaces the arguments passsed to the `Info`, `Warn` and `Error` methods with human friendly strings. Currently that applies only to Kubernetes objects, which are replaced by strings containing the namespace and name. For example, a call like this:
```
config := &corev1.ConfigMap{
ObjectMeta: metav1.ObjectMeta{
Namespace: "my-ns",
Name:	   "my-name",
},
}
console.Info("Object '%s' doesn't exist")
```
Will result in the following output:
```
I: Object 'my-ns/my-name' doesn't exist
```

NO-ISSUE: Replace console args

---

ztp/internal/enricher.go

This patch adds a missing error check in the enricher.

NO-ISSUE: Add missing error check in enricher

---

hack/deploy-hub-local/build-hub.sh

Update kcli support
- Versions:
- Hardware:

Align with latest kcli

---

deploy-worker/change_def_route.sh

The file it points to doesn't exist.
- Versions:
- Hardware:

Remove a stale symlink.

---

Makefile
deploy-disconnected-registry/oc-mirror-config-edgecluster.yaml
deploy-disconnected-registry/oc-mirror-config-hub.yaml
deploy-edgecluster/render_edgeclusters.sh
deploy-lvmo/deploy-hub.sh
deploy-lvmo/deploy.sh
deploy-lvmo/manifests/03-LVMO-Subscription.yaml
deploy-lvmo/manifests/05-Hub-PVC.yaml
deploy-lvmo/verify.sh
deploy-lvmo/verify_hub.sh
deploy-odf/manifests/04-MCG-StorageCluster.yaml
hack/deploy-hub-local/build-hub.sh
hack/deploy-hub-local/create-vm-sno.yml
hack/deploy-hub-local/create-vm.yml

Switch ZTPFW to 4.12

---

documentation/ztp-for-factories/ztp-install-openshift-pipelines.adoc

It actually fails the curl command.
- Versions:
- Hardware:

Removing the -K argument

---

.github/workflows/check-cli.yml

This patch change the GitHub workflows so that the CLI tests aren't executed if there are no changes to the CLI code.

NO-ISSUE: Don't check CLI if it didnt' change

---

pipelines/resources/deploy-ztp-edgeclusters-connected.yaml
pipelines/resources/deploy-ztp-edgeclusters.yaml
ztp/internal/data/cluster/objects/030-agentclusterinstall.yaml
ztp/internal/data/cluster/objects/070-nmstateconfig.yaml
ztp/internal/data/cluster/objects/080-bmc-secret.yaml
ztp/internal/data/cluster/objects/090-baremetalhost.yaml

Remove the `deploy-worker` step as it is now possible to deploy 4-node clusters using 4.12 and MCE 2.7
- Versions:
- Hardware:

Deploy 4-nodes clusters in one step

---

documentation/ztp-for-factories/ztp-for-factory-development.adoc
documentation/ztp-for-factories/ztp-for-factory-installation-workflow.adoc

This is to avoid confusion and to ave consisent args.
- Versions:
- Hardware:

Aligning the documentation with the same args.

---

ztp/internal/enricher.go

This patch adjust the log levels and content of log messages generated by the enricher so that they are more relevant and useful.

NO-ISSUE: Adjust some log levels

---

documentation/ztp-for-factories/ztp-install-factory-edge-pipeline.adoc

Enhance the requirements for the edge cluster.

---

ztp/internal/applier_test.go
ztp/internal/cmd/create_cluster_cmd_test.go
ztp/internal/config/loader_test.go
ztp/internal/enricher_test.go
ztp/internal/logging/flags.go
ztp/internal/templating/engine_test.go
ztp/internal/testing/template.go
ztp/internal/text/dedent.go
ztp/internal/text/dedent_test.go
ztp/internal/text/suite_test.go

This patch moves the `Dedent` function that was part of the `testing` package to a new `text` package, so that it can be used outside of tests.

NO-ISSUE: Move `Dedent` to new `text` package

---

ztp/internal/data/cluster/objects/090-baremetalhost.yaml

Worker BMH should have the role annotation set
- Versions:
- Hardware:

Add role annotation for workers

---

ztp/internal/applier.go
ztp/internal/cmd/create/cluster/create_cluster_cmd.go
ztp/internal/cmd/create/create_cmd.go
ztp/internal/cmd/create/lso/create_lso_cmd.go
ztp/internal/data.go
ztp/internal/data/dev/crds/0160_localvolume.yaml
ztp/internal/data/lso/objects/0010-namespace.yaml
ztp/internal/data/lso/objects/0020-operatorgroup.yaml
ztp/internal/data/lso/objects/0030-subscription.yaml
ztp/internal/data/lso/objects/0040-localvolume.yaml
ztp/internal/data/lso/scripts/wipe.sh
ztp/internal/gvks.go

This patch adds the new `ztp create lso` command that deploys the local storage operator on the edge clusters.

NO-ISSUE: Add `create lso` command

---

ztp/internal/cmd/delete/delete_cmd.go
ztp/internal/cmd/delete/metallb/delete_metallb_cmd.go

This patch adds a new `ztp delete metallb` command that deletes the metal load balancer.

NO-ISSUE: Add `delete metallb` command

---

ztp/internal/cmd/delete/delete_cmd.go
ztp/internal/cmd/delete/ui/delete_ui_cmd.go
ztp/internal/data/ui/objects/0020-clusterrolebinding.yaml
ztp/internal/data/ui/objects/0030-deployment.yaml
ztp/internal/data/ui/objects/0040-oauthclient.yaml
ztp/internal/data/ui/objects/0050-service.yaml
ztp/internal/data/ui/objects/0060-route.yaml

This patch adds a new `ztp delete ui` command that deletes the user interface components.

NO-ISSUE: Add `delete ui` command

---

ztp/internal/cmd/create/cluster/create_cluster_cmd.go
ztp/internal/cmd/create_cluster_cmd_test.go

Currently the `ztp create cluster` command exists with an error code when the `Failed` condition of the cluster changes to `True`, but it doesn't exit if the `.status.debugInfo.state` changes to `error`. This patch changes it so that it also exists with an error code in that case.
Related: https://issues.redhat.com/browse/MGMT-13854
Tested manually and with the included unit tests.

MGMT-13854: Fail installation if it moves to `error`

---

ztp/internal/cmd/delete/ui/delete_ui_cmd.go

There is no need to repeat the calculation of the host because that isn't necessary for deleting the objects.

NO-ISSUE: Simplify `delete ui` command

---

ztp/internal/cmd/create/cluster/create_cluster_cmd.go

Currently the CLI prints the cluster status when it receives an event inicating some change in the cluster, even if the status itself hasn't changed. This patch fixes that, so that it will only print the state when it is different to the previous state.

NO-ISSUE: Don't repeat status change messages

---

ztp/internal/cmd/create/metallb/create_metallb_cmd.go

This patch changes the `create metallb` command so that it waits for the API to be reachable before finishing.

NO-ISSUE: Wait for API reachability in `create metallb`

---

ztp/internal/cmd/create_cmd.go
ztp/internal/cmd/dev/dev_templates.go
ztp/internal/cmd/dev/templates/setup/crds/0170_backingstore.yaml
ztp/internal/cmd/odf/create_odf_cmd.go
ztp/internal/cmd/odf/odf_templates.go
ztp/internal/cmd/odf/templates/objects/0010-namespace.yaml
ztp/internal/cmd/odf/templates/objects/0020-operatorgroup.yaml
ztp/internal/cmd/odf/templates/objects/0030-subscription.yaml
ztp/internal/cmd/odf/templates/objects/0040-storagecluster.yaml
ztp/internal/gvks.go
ztp/internal/models/properties.go

This patch adds a new `create odf` command that deployes the OpenShift Data Foundation operator to the target cluster.

NO-ISSUE: Add `create odf` command

---

ztp/internal/cmd/metallb/create_metallb_cmd.go

The `create metallb` command waits till the API is reachable via metal load balancer, but it does this reusing a client that it creates outside of the retry loop. This client will fail to create the first time because it sends requests to get the API metadata that will fail. To fix that issue this patch changes that command so that it creates a new client for each iteration of the retry loop.

NO-ISSUE: Fix waiting for metal load balancer

---

pipelines/resources/deploy-ztp-edgeclusters-connected.yaml
pipelines/resources/deploy-ztp-edgeclusters-sno-connected.yaml
pipelines/resources/deploy-ztp-edgeclusters-sno.yaml
pipelines/resources/deploy-ztp-edgeclusters.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-lso.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-odf.yaml

This patch changes the pipelines so that the `deploy-lso` and `deploy-odf` steps use the CLI instead of the shell scripts.

NO-ISSUE: Use CLI in `deploy-lso` and `deploy-odf` steps

---

pipelines/resources/deploy-ztp-edgeclusters-connected.yaml
pipelines/resources/deploy-ztp-edgeclusters-sno-connected.yaml
pipelines/resources/deploy-ztp-edgeclusters-sno.yaml
pipelines/resources/deploy-ztp-edgeclusters.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-ui.yaml

This patch changes the pipelines to use the CLI to deploy the UI.

NO-ISSUE: Use CLI in `deploy-ui` step

---

ztp/internal/cmd/registry/create_registry_cmd.go

Currently the auth added to the pull secret when the registry is added contains no user name and the Quay token. That it wrong, it should contain the admin user name and the password. This patch fixes that.

NO-ISSUE: Fix generation of registry auth

---

ztp/internal/cmd/create_cmd.go
ztp/internal/cmd/delete_cmd.go
ztp/internal/cmd/dev/dev_templates.go
ztp/internal/cmd/dev/templates/setup/crds/0180_lvmcluster.yaml
ztp/internal/cmd/lvmo/create_lvmo_cmd.go
ztp/internal/cmd/lvmo/delete_lvmo_cmd.go
ztp/internal/cmd/lvmo/lvmo_templates.go
ztp/internal/cmd/lvmo/templates/objects/0010-namespace.yaml
ztp/internal/cmd/lvmo/templates/objects/0020-operatorgroup.yaml
ztp/internal/cmd/lvmo/templates/objects/0030-subscription.yaml
ztp/internal/cmd/lvmo/templates/objects/0040-lvmcluster.yaml
ztp/internal/cmd/lvmo/templates/scripts/wipe.sh
ztp/internal/gvks.go

This patch adds a new `create lvmo` command that deploys the logical volume manager operator.

NO-ISSUE: Add `create lvmo` command

---

pipelines/resources/deploy-ztp-edgeclusters-sno.yaml
pipelines/resources/deploy-ztp-edgeclusters.yaml

It always times out in our setup.
- Versions:
- Hardware:

Increasing the timeout for olm-mirror

---

shared-utils/common.sh

Fixes #847
- Versions: OpenShift v12
- Hardware: Supermicro Boards
- [ X] I have performed a self-review of my own code
- [ X] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ X] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use …

edit 'contains' that the subnets 192.168.7[0..9] are not matched anymore
