rh-ecosystem-edge/ztp-pipeline-relocatable

.flake8
.github/workflows/release.yml
.github/workflows/update_semver.yml
.isort.cfg
.releaserc.json
test-requirements.txt

Use GHA for automating release tagging so that 'v1.0.0' automatically creates 'v1.0', 'v1', and newer tags will update the pointers

GHA for release management

---

deploy-ocs/deploy.sh

Fix extracting the kubeconfig for spoke.

---

shared-utils/verify_preflight.sh

In error message there is a typo with **Persisten** correcting it to **Persistent**

fixing typo on Persisten in verify_preflight.sh

---

.github/workflows/deploy-ztp-hub.yml
.github/workflows/deploy-ztp-spokes.yml
deploy-disconnected-registry/mirror-snapshot.sh
deploy-hub-configs/deploy.sh

The Hub registry must be restored if there's an existing  tarball  and we're not syncing it again

Restore hub registry when not syncing

---

finish-deployment/deploy.sh

Adding function to copy the kubeconfig properly to the Spoke Master Nodes
Adding function to copy the kubeconfig properly to the Spoke Master Nodes
Fixes #82 

Closes #82 - Adding function to copy the kubeconfig properly to the masters

---

deploy-spoke/render_spokes.sh

According to the requirements in the architecture
doc, fips should be set to true.

Enable fips

---

deploy-spoke/verify.sh

```
[deploy-spokes] >> Waiting for ACI
[deploy-spokes] Spoke: spoke0-cluster
[deploy-spokes] Current: Finalizing cluster installation
[deploy-spokes] Desired State: Cluster is Installed
[deploy-spokes]
[deploy-spokes] Timeout waiting for AgentClusterInstall spoke0-cluster on condition .status.conditions.Completed
[deploy-spokes] flags cannot be placed before plugin name: --kubeconfig=/workspace/ztp/kubeconfig
[deploy-spokes] Expected: True Current:
container step-deploy-spokes has failed  : [{"key":"StartedAt","value":"2022-03-15T15:45:55.015Z","type":3}]
```

fixing check after timeout on spoke deployment

---

.github/workflows/ui.yml
ui/package.json

Parallel execution of the "yarn install" fails in the GitHub actions. Let's execute it sequentially.

UI: Fix random failing of "yarn install" in CI

---

ui/frontend/src/components/PersistPage/constants.ts
ui/frontend/src/components/PersistPage/persist.ts
ui/frontend/src/components/PersistPage/persistServices.ts
ui/frontend/src/components/PersistPage/resourceTemplates.ts

Ingress/API AddressPool resources are expected to be already pre-created by factory.
This patch patches existing resources if possible.
- Versions:
- Hardware:

UI: Patch existing AddressPool instead of creating a new one

---

deploy-spoke/deploy.sh

Patching the provisioning causes the metal3 pod to restart.
This interferes with creating bmh instances.
- Versions:
- Hardware:

Patch provisioning after all crs were created.

---

ui/frontend/src/components/DownloadSshKeyPage/DownloadSshKey.tsx

In case of error when downloading the SSH key, the user can proceed farther in the wizard.
Otherwise the transition is blocked until the key is downloaded.

Allow Next when SSH key ydownload fails

---

Makefile
deploy-ocs/manifests/04-OCS-StorageCluster.yaml
hack/deploy-hub-local/create-vm.yml

This update will fix our virtual environments with just disk of 50Gb-x4 per node, we need to ensure we will not put more size than the hypervisor could host. This only applies where OCS is deployed, so only affects the Spoke
Fixes [MGMT-10096](https://issues.redhat.com/browse/MGMT-10096) (issue)
Tested in Flavio3 Node, after 16h of use the spoke cluster behaves good.
PS: The worker task failed it's another non-related issue

fix: MGMT-10096 - Avoid storage overcommit when OCS is deployed

---

pipelines/bootstrap.sh

Removing the need of impersonation on root to execute the `bootstrap.sh` script

fix: Root is not necessary to execute the bootstrap script, removing

---

hack/deploy-hub-local/lab-sushy.service

When enabling sushy.service using lab-sushy.sh, systemd complains because the systemd unit does not have an Install section.
- [X ] Bug fix (non-breaking change which fixes an issue)

Fix systemd error when enabling sushy

---

ui/backend/src/common/resources/deployment.ts
ui/backend/src/common/resources/index.ts
ui/backend/src/common/resources/oauthclient.ts
ui/backend/src/common/resources/pod.ts
ui/backend/src/common/resources/route.ts
ui/backend/src/constants.ts
ui/backend/src/endpoints/changeDomain.ts
ui/backend/src/endpoints/liveness.ts
ui/backend/src/endpoints/readiness.ts
ui/backend/src/k8s/json-request.ts
ui/backend/src/k8s/oauth.ts
ui/backend/src/k8s/respond.ts
ui/backend/src/resources/deployment.ts
ui/backend/src/resources/oauthclient.ts
ui/backend/src/resources/route.ts
ui/frontend/src/components/ActionCountDown/index.tsx
ui/frontend/src/components/PersistPage/PersistPageBottom.tsx
ui/frontend/src/components/PersistPage/constants.ts
ui/frontend/src/components/PersistPage/persist.ts
ui/frontend/src/components/PersistPage/persistServices.ts
ui/frontend/src/components/PersistPage/utils.ts
ui/frontend/src/components/Settings/SettingsPageRight.tsx
ui/frontend/src/index.tsx
ui/frontend/src/resources/pod.ts

Avoid bling patching all of them.
TODO:
In a nutshell:
- remove blind update of all routes, modify them selectively
- be more talkative about progress in the UI (but this still needs improvement, i.e. progress bar)
- block UI transition to new domain on a serie of predicates to be met first
- implement first "blocking-predicate" - wait for ZTPFW UI pod to be ready and serving **new** domain
- when saving API IP change, block on failing livenessProbe
- comment-out deletion of kubeadmin (will be properly handled in #195)
- skip querying `/.well-known/oauth-authorization-server` for auth endpoint in favour of calculating it from cluster domain (kind of hardcoding) - did not work reliably after domain change
- make liveness/ready probes dependant on reaching API instead of auth server
- …

Patch routes selectively

---

deploy-spoke/csr_autoapprover.sh

Do not delete the kubeconfig stored in the spoke filesystem, nor disable csr-approver.service.
In a later PR we'll modify the kubeconfig to not be system:admin but only have the csr-approver clusterrole.

Do not disable csr-autoapprover service

---

deploy-spoke/render_spokes.sh
finish-deployment/deploy.sh

Masking this unit allows us to avoid the image cache deletion on the nodes once the enclosure is relocated.
The problem happens when a power cycle appears and the service crio-wipe deletes the node images stored in cache. 
This issue becomes a bigger issue, knowing that the cluster is disconnected and the nodes are using their own registry to boot the pods up.
This is the main reason for this improvement.
In addition I've refactored the save_files function using the @flaper87 method.
Fixes [MGMT-10240](https://issues.redhat.com/browse/MGMT-10240)
- Needs Manual Testing on Flavio3
- Avoid CI Testing because of virtual worker deployment step broken (This step comes later)

MGMT-10240 - Mask crio-wipe systemd unit

---

documentation/ztp-for-factories/ztp-for-factory-spokes-yaml.adoc

[Documentation_PR] Adding `root_disk: sda` parameter under `spokes.yaml` file 
Fixes #237 

Adding  under spokes.yaml file

---

hack/set-motd/README.md
hack/set-motd/go.mod
hack/set-motd/main.go

Add a new feature: set-motd
This binary sets /etc/motd or a given custom path to a custom programmable message, so a given server will show the message that it's being used.
In the future:
- It will be installed by ansible hypervisor scripts in /root/bin/set-motd for manual use
- It will be invoked from CI to set the PR currently being tested.

Add set-motd utility

---

.github/workflows/set-motd.yml

New feature: Sets /etc/motd using /root/bin/set-motd when a job is in progress.

feat(ci): set motd when a worker is in use

---

hack/set-motd/main.go

Fixed the amount of args "set-motd set" can receive, we don ´t need an upper limit since -motd should receive messages as long as needed.

fix(setmotd): removing max args in setmotd set

---

hack/deploy-hub-local/ansible/tasks/base/02-bin-utils.yaml

When re-running the playbook it fails in the git clone step because the dest dir already exist. 
This change ensures the previous code is deleted before cloning again.

fix(ansible): clean repo before cloning

---

hack/deploy-hub-local/ansible/tasks/files/bashrc

For some reason having an 'echo -e "x"' in .bashrc breaks ansible and it cannot retrieve the python interpreter correctly or any of the setup variables. 
Reverting this change from main and it will be tested extensively in dev branch.

fix(ansible): bashrc messages break ansible

---

pipelines/resources/deploy-ztp-edgeclusters.yaml

Workers were accidentally commented out while working on the GPU feature
- Versions:
- Hardware:

Re-enable worker after it was accidentally disabled

---

deploy-disconnected-registry/deploy.sh

This check expect the routes in the project ztpfw-registry to be exactly 3, which apparently now is incorrect (changes in quay operator?).
Now, it will check for 3 routes or more.
```
root:flavio2 : [system:admin@edge] ~  
$ oc get routes
NAME                                HOST/PORT                                                                                  PATH   SERVICES                            PORT    TERMINATION     WILDCARD
ztpfw-registry-quay                 ztpfw-registry-quay-ztpfw-registry.apps.edgecluster0-cluster.alklabs.local                        ztpfw-registry-quay-app             http    edge/Redirect   None
ztpfw-registry-quay-builder         ztpfw-registry-quay-builder-ztpfw-registry.apps.edgecluster0-cluster.alklabs.local                ztpfw-registry-quay-app …
```

fix(registry): fix the registry route check

---

.github/workflows/testing-pr.yml

Skip UI build generation errors in the meantime
related #332

ci(testing-pr.yaml): skip UI generation errors to not block other tests

---

deploy-odf/manifests/04-ODF-StorageCluster.yaml
hack/deploy-hub-local/create-vm.yml

Change the VM disk and the request in the storagecluster manifest to 75gb disk size
Fixes # https://issues.redhat.com/browse/MGMT-10251
Tested manually in Flavio1 to verify with @achuzhoy before testing with the CI
Also has been tested after a day just to ensure the size of disks is OK and not increasing
```
cluster:
id:     e96b1089-7ca1-4434-8233-e604ffadc873
health: HEALTH_OK  services:
mon: 3 daemons, quorum a,b,c (age 2m)
mgr: a(active, since 22h)
mds: 1/1 daemons up, 1 hot standby
osd: 12 osds: 12 up (since 21h), 12 in (since 23h)
rgw: 1 daemon active (1 hosts, 1 zones)  data:
volumes: 1/1 healthy
pools:   11 pools, 465 pgs
objects: 54.33k objects, 110 GiB
usage:   341 …
```

fix: mgmt-10251-change default size vm and odf storagecluster manifest to 1 

---

.github/workflows/broken-link-check.yml

Fix broken-link-check to not consider duplicate links and opening false positives issues with errors `HTTP_403, HTTP_404`
Issue upstream https://github.com/technote-space/broken-link-checker-action/issues/149
Fix upstream https://github.com/technote-space/broken-link-checker-action/pull/142

ci(broken-link): use v2.3.0

---

hack/clean/clean-libvirt-pool.sh

Include more options:
- dry-run: to check images/disk/isos to be deleted
- now: to run clean-libvirt-pool
Now the logic takes in account more use cases to prevent images/isos/disk from being mistakenly deleted.

internal(clean-scripts): take in account more use cases and options

---

hack/clean/clean-libvirt-pool.sh

- Remove `set -o nounset` so not declared variables won't make this script to fail.
- Control if $1 is present, otherwise show usage
Fixes failing on unbound $1
Previously the failures where $1 wasn't declared:
```
$ hack/clean/clean-libvirt-pool.sh 
hack/clean/clean-libvirt-pool.sh: line 42: $1: unbound variable
```
After the changes:
- With $1 not present
```
$ hack/clean/clean-libvirt-pool.sh 
Usage: [dry-run|now]
```
- With an invalid $1
```
$ hack/clean/clean-libvirt-pool.sh whatever
Usage: [dry-run|now]
```
- With a valid $1
```
$ hack/clean/clean-libvirt-pool.sh dry-run
############### hack/clean/clean-libvirt-pool.sh dry-run
############### resources in use - won't be deleted
ls /var/lib/libvirt/images | grep -Ev …
```

clean(libvirt-pool): control unbound

---

.github/workflows/release.yml

Reverts rh-ecosystem-edge/ztp-pipeline-relocatable#391 as per https://github.com/actions/setup-python/issues/421

Revert "build(deps): bump actions/setup-python from 3 to 4"

---

Makefile

Sometimes during a make clean, the cleaning process is stuck forever.
This is because deleting objects in Kubernetes/OCP follows a cascade pattern:
- We try to delete the namespace
- The namespace tries to finalize all the resources under it
- The BaremetalHost in the namespace calls their own finalizer at metal3 API, and the API starts the deprovisioning
- This deprovisioning under certain circunstamces never ends
By deleting first the vm's:
- The deprovisioning procedure is skipped (we don´t need it as the vm does not exist, anyway)
- Rest of the cleaning is performed as usual

fix(Makefile): reverse clean order

---

.github/workflows/ui.yml

An attempt to fix the triggering of the ui workflow for every pull_request, and also fix the first if which is faulty and GHA constantly complains about:
```
[Invalid workflow file: .github/workflows/ui.yml#L17](https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/actions/runs/2503700143/workflow)
The workflow is not valid. .github/workflows/ui.yml (Line: 17, Col: 9): Unexpected end of expression: ')'. Located at position 160 within expression: (!contains(github.event.label.name, 'skip-ci-ui') || github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'test-ci-ui')
```

ci(ui): fix first if

---

ui/frontend/src/components/K8SStateContext.tsx
ui/frontend/src/components/PersistPage/PersistPageBottom.tsx
ui/frontend/src/components/PersistPage/persist.ts

If the user navigates to the /persist page either directly without providing
data first or just by hitting F5 during persistence, the actual persist() routine
is skipped and the user is navigated to the /welcome screen instead.
This fix avoids blind saving of default data.
- Versions:
- Hardware:

MGMT-10892 Safe navigation to the /wizard/persist page for no change

---

images/Containerfile.pipeline

Override for BZ 2073197 to override permissions https://bugzilla.redhat.com/show_bug.cgi?id=2073197#c19
Related: https://github.com/openshift/machine-config-operator/issues/1349
Apparently, by mistake,  a change in  RHCOS image does try to verify signatures for the images, which are not currently mirrored or even provided, and this causes an issue.
There's an upstream issue listed to get this solved, but as a workaround we're disabling verification in Edge clusters via an ignition file and might in addition require a change in the installer image being used until RHCOS has the changes reverted and the related tooling is updated to mirror signatures, etc.

fix(edgeclusters.sh): Workaround BZ 2073197 issue with signatures on containers

---

Makefile

Reverts rh-ecosystem-edge/ztp-pipeline-relocatable#410
This PR seems to be breaking the clean-up process quite a bit.
@fbac and I chatted a bit about it and he mentioned that one of the motivations behind the original PR was to avoid doing the cleanup. That said, cleanup should not happen since we have `automaticCleaning` set to false. Removing the VMs from metaal3 is causing the finalizers to constantly get stuck, which makes the cleanup process slow and error prone.
So, we either go this way or we start removing the finalizers as a hack.

Revert "fix(Makefile): reverse clean order"

---

.pre-commit-config.yaml

Add shellcheck to pre-commit to help reducing new files to break CI from PR: #305

ci(.precommit): Add shellcheck

---

shared-utils/common.sh

If the remote registry is quay, we don't have user/pass as we only use the pull secret, avoid using them.
Fixes #452

fix: Make quay.io use pull secret only

---

deploy-metallb/deploy.sh

Fix the issue with the nmstate operator:
````
account:openshift-nmstate:nmstate-operator" cannot list resource "nodes" in API group "" at the cluster scope
E0713 15:43:47.466609       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:250: Failed to watch *v1.Node: failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:openshift-nmstate:nmstate-operator" cannot list resource "nodes" in API group "" at the cluster scope
````
Fixes # reported the bug here: https://bugzilla.redhat.com/show_bug.cgi?id=2106840
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also …

fix the bug for metallb operator

---

hack/deploy-hub-local/lab-nfs.sh

NFS setup script removes the folder, this makes it harder to do custom configurations that depends on symlinks, etc.
This PR makes the cleaning to be less destructive, just removing the contents but not the folder (or symlink)

ci(nfs): do wipe instead of full removal

---

Makefile

The problem is that with existing code, we're not able to launch a 1.10.3 tag using RELEASE=1.10.3 make deploy... command:
```
ifneq ($(BRANCH),)
BRANCH := $(RELEASE)
endif
```
always will be launched from a branch and release never will be selected. 
To fixed we've created a TAG variable in order to:
- TAG=1.10.3 make deploy...  -> to deploy an specific image from a tag (previous built)
- make deploy... -> Inside a branch in your repo to deploy an specific branch image (previous built)
- Versions:
- Hardware:

Fix: Makefile issue with release tag

---

deploy-worker/render_worker.sh

On BM agents can take more than 120s to come up. This change will help us wait in loops of 1 minute for, at most, 10 mins
- Versions:
- Hardware:

NO-ISSUE: Add retries when waiting for worker agent

---

deploy-worker/render_worker.sh

On BM agents can take more than 120s to come up. This change will help us wait in loops of 1 minute for, at most, 10 mins
Backport for #480 
Co-authored-by: Flavio Percoco <flavio@redhat.com>
(cherry picked from commit bf105c9f40b65e794894d90782ffcb7503ae445f)

NO-ISSUE: Add retries when waiting for worker agent 

---

deploy-odf/deploy.sh
deploy-odf/verify.sh
hack/deploy-hub-local/create-vm.yml

Default to RBD vs CephFS as per https://issues.redhat.com/browse/MGMT-10381  to reduce the chances of locking errors and some of the issues seen.
Fixes #424

MGMT-10381: Use rados-gw nstead of CephFS as recommended by the ODF team

---

.github/workflows/testing-pr-compact.yml
ui/README.md

Reverts rh-ecosystem-edge/ztp-pipeline-relocatable#483

Revert "Require CI UI build to pass"

---

deploy-disconnected-registry/ocp-sync.sh
deploy-disconnected-registry/olm-sync.sh
pipelines/resources/common/common-pre-flight-edgeclusters.yaml
pipelines/resources/common/common-pre-flight.yaml
pipelines/resources/contrib/contrib-gpu-operator.yaml
pipelines/resources/contrib/contrib-template.yaml
pipelines/resources/deploy-ztp-edgeclusters-sno.yaml
pipelines/resources/deploy-ztp-edgeclusters.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-disconnected-registry-edgeclusters-ocp.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-disconnected-registry-edgeclusters-olm.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-disconnected-registry-edgeclusters-ps.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-disconnected-registry-edgeclusters.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-edgecluster.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-icsp-edgeclusters-post.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-icsp-edgeclusters-pre.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-lso.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-lvmo.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-metallb.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-odf.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-ui.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-workers.yaml
pipelines/resources/edgeclusters/edgecluster-detach-cluster.yaml
pipelines/resources/hub/hub-deploy-acm.yaml
pipelines/resources/hub/hub-deploy-disconnected-registry.yaml
pipelines/resources/hub/hub-deploy-httpd-server.yaml
pipelines/resources/hub/hub-deploy-hub-config.yaml
pipelines/resources/hub/hub-deploy-icsp.yaml
pipelines/resources/hub/hub-deploy-mce.yaml
pipelines/resources/hub/hub-save-config.yaml
shared-utils/common.sh

It is currently not possible to run multiple deployments in parallel because ZTPFW re-uses the same `build` dir for all pipelines. This PR creates a dedicated `OUTPUTDIR` using the `pipeline-name/task-name` of the specific run. 
`all` is used in case of a no pipeline (task ran in isolation)
Example of the build dir:
- Versions:
- Hardware:

NO-ISSUE: Use a dedicated build dir per pipeline/task

---

shared-utils/common.sh

When we re-run the pipeline after the edgecluster was already
deployed, the key needs to be extracted from a secret instead
of creating a new one.
- Versions:
- Hardware:

We don't need to create a new RSA key if one existed.

---

pipelines/resources/common/pvc-template.yaml

There should be a default storageclass in the cluster when this manifest is applied. No need to hard-code the storageclass.
@achuzhoy tested it :)
- Versions:
- Hardware:

NO_ISSUE: Let PVC use the default storageclass

---

deploy-edgecluster/verify.sh
finish-deployment/deploy.sh

Currently the RSA key is stored at the very end. If the pipeline
fails sooner - the key is re-generated but the new SSH key won't
work with the installed nodes and tasks using ssh to connect to
nodes will fail.
- Versions:
- Hardware:

We should store the RSA key for the edge cluster sooner.

---

deploy-lso/deploy.sh
deploy-lvmo/deploy.sh
shared-utils/common.sh

The deployment of LVMO operator in the SNO edgecluster require that the local disk are clean, hence it is mandatory to wipe the disks before install the operator and create the lvmcluster object.
Below is the output of the pipelie `deploy-pipeline-edgecluster-sno` , only the task deploy-lvmo where the disks are wiped before install the operator.

wipe disks as a shared function

---

Makefile
deploy-disconnected-registry/common.sh
deploy-disconnected-registry/deploy.sh
deploy-disconnected-registry/manifests/custom-registry-endpoint.yaml
deploy-disconnected-registry/manifests/pvc-registry.yaml
deploy-disconnected-registry/ocp-sync.sh
deploy-disconnected-registry/quay-manifests/quay-user-update.json
deploy-disconnected-registry/verify.sh
deploy-edgecluster/configure_disconnected.sh
deploy-hub-configs/deploy.sh
deploy-odf/deploy.sh
documentation/ztp-for-factories/ztp-hub-factory-pipeline.adoc
documentation/ztp-for-factories/ztp-install-factory-edge-pipeline.adoc
documentation/ztp-for-factories/ztp-install-factory-pipeline.adoc
hack/custom_registry/01_deploy_registry.sh
hack/custom_registry/02_update_pullsecret.sh
hack/custom_registry/README
hack/deploy-hub-local/build-edgecluster.sh
hack/deploy-hub-local/build-hub.sh
pipelines/resources/common/kustomization.yaml
shared-utils/common.sh

This is the revert of the revert so we can test it, and build on top of it
Reverts rh-ecosystem-edge/ztp-pipeline-relocatable#550
Content/Features/Bugs of this PR:
- Fix some bugs discovered in the original Custom Registry (auth issues with PullSecret and unbound variables when we don't use CustomRegistry)
- New Folder hack/custom_registry where some new **Scripts** and **README** enables the possibility to deploy in a lab a custom registry to be tested. 
- Remove lab-nfs.sh + bootstrap step to create pv, because we're using now lvmo instead of NFS in the hub.
- Adding the task to deploy lvmo in the hub as a task in the MakeFile as pre-requirement:
- Modify the Makefile to enable the custom-registry as new targets (hub and edge) adding the REGISTRY as param instead of env variable:
- No …

Revert "Revert "MGMT-10030: Custom registry ""

---

pipelines/bootstrap.sh
pipelines/manifests/01-subscription.yaml

This PR is related to the 4.11 migration but focuses on the OCP pipeline upgrade first. It fixes two issues preventing us from upgrading to the newest OCP pipeline version

MGMT-12539: Allow to use newer versions of OCP pipeline

---

deploy-disconnected-registry/olm-sync.sh

If the directory is missing the secret isn't copied to the right place and the opm index prune command fails.
- Versions:
- Hardware:

Fix the issue with opm index prune.

---

deploy-worker/render_worker.sh

Skip `deploy-workers` for edgeclusters that don't have a worker defined.
- Versions:
- Hardware:

Exit from workers task if no workers defined

---

deploy-edgecluster/change_def_route.sh
deploy-edgecluster/render_edgeclusters.sh

This is a small tweak to how we manage the networks so that we can do a deployment on 4.11 too with isolated networks and 2 nics.
It fixes a bug on the iface hint for single nic
Single nic test:
- Versions:
- Hardware:

Initial changes for 4.11

---

.github/workflows/check-cli.yml
ztp/go.mod
ztp/go.sum

Currently the GitHub action that checks the CLI installs a version of the `ginkgo` tool that may not match the version that the tests are compiled with. To address that this patch changes the action so that it checks the version in use with the `go list ...` command and installs it.

Use matching ginkgo version in GitHub actions

---

.github/workflows/check-cli.yml

The `golangci-lint` GitHub action is frequently failing with an error message like this:
```
level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
```
The default timeout is one minute. This patch increases the timeout to five minutes.
Tested in the GitHub action.

NO-ISSUE: Increase golangci-lint timeout

---

ztp/internal/config.go
ztp/internal/jq.go
ztp/internal/jq_test.go

This patch adds tests for the object that is used to run `jq` queries.
Run the new tests.

NO-ISSUE: Add testss for the `jq` object

---

ztp/internal/template.go
ztp/internal/template_test.go

This patch adds a template object that will be used to generate Kubernetes objects from embedded templates.
Tested using the included tests.

NO-ISSUE: Add template object

---

ztp/internal/testing/environment.go
ztp/internal/testing/environment/crds/0000_example.yaml
ztp/internal/testing/environment/objects/0000_example.yaml

This patch adds support for automatically creating CRDs and objects in the testing environment. The CRDs are defined with YAML files inside the `internal/testing/environment/crd` directory, and the objects with YAML files inside `internal/testing/environment/objects`. See the examples there.

NO-ISSUE: Add support for creating CRDs and objects in testing env

---

ztp/internal/jq.go
ztp/internal/jq_test.go

This patch adds to the JQ object methods that read the input from strings or array of bytes.

NO-ISSUE: Add JQ methods to read from strings and bytes

---

ztp/internal/tool.go
ztp/main.go

This patch adds methods to get and set the environment variables of the tool. This is intended to simplify tests that use environment variables, as it will be much easier to prepare a fake set of environment variables.

NO-ISSUE: Add methods to get/set tool env

---

ztp/internal/templating/engine.go
ztp/internal/templating/engine_test.go

Currently when a template uses the `execute` function to execute another template the code doesn't check if that template exists. The result is a nil pointer exception that is difficult to understand. This patch changes the code so that it checks that condition and generates an error message that is easier to understand.
Added a test.

NO-ISSUE: Check existence of called template

---

ztp/internal/testing/fs.go

Currently the content of the files passed to the `TmpFS` function need to be strings. That complicates passing values that are arrays of bytes. This patch changes the function so that it also accepts arrays bytes.

NO-ISSUE: Support byte array as content of testing TmpFS

---

ztp/internal/client.go
ztp/internal/client_test.go

Currently the Kubernetes API client loads the configuration using the `clientcmd` package. That in turn uses the `KUBECONFIG` environment variable. That complicates testing because it is difficult to change the values of the environment variables and then restore them after running the test. To make that simpler this patch changes the client builder so that it receives a map containing the environment, and uses those variables instead of `os.LookupEnv`.

NO-ISSUE: Explicitly load kbueconfig in client

---

ztp/internal/cmd/dev/cleanup/dev_cleanup_cmd.go
ztp/internal/cmd/dev/dev_cmd.go
ztp/internal/cmd/dev/setup/dev_setup_cmd.go
ztp/internal/cmd/edgecluster/edgecluster_cmd.go

This patch adds a new `dev cleanup` command that removes all the objects created by the `dev setup` command as well as all the objects created for clusters. This simplifies the development setup, which should be now like this:
```
$ # Create the development cluster:
$ kind create cluster
$ # Create the CRDs and objects that simulate the ACM hub:
$ ./ztp dev setup
$ # Run tests, or run the `edgecluster` command manually:
$ ginkgo run -r
$ ./ztp edgecluster
$ # Clean the development cluster:
$ ./ztp dev cleanup
```

NO-ISSUE: Add `dev cleanup` command

---

ztp/internal/cmd/dev/cleanup/dev_cleanup_cmd.go
ztp/internal/cmd/edgecluster/edgecluster_cmd.go
ztp/internal/cmd/edgecluster_cmd_test.go
ztp/internal/cmd/version_cmd_test.go
ztp/internal/enricher.go
ztp/internal/errors.go
ztp/internal/gvks.go
ztp/internal/logging/logger.go
ztp/internal/tool.go
ztp/main.go

This patch adds the `--wait` option to the `edgecluster` command. This option tells the command how long to wait till the clusters are ready. The default is one hour. Setting it to zero means that the command will not wait at all.

NO-ISSUE: Add `--wait` option to `edgecluster`

---

ztp/internal/cmd/dev/cleanup/dev_cleanup_cmd.go
ztp/internal/cmd/dev/dev_cmd.go
ztp/internal/cmd/dev/setup/dev_setup_cmd.go
ztp/internal/cmd/version/version_cmd.go

The files in the `cmd/...` packages have all `cmd` as package name. That doesn't have any real impact, but it is wrong. This patch fixes thos package names.

NO-ISSUE: Fix command package names

---

ztp/internal/cmd/edgecluster/edgecluster_cmd.go
ztp/internal/enricher.go
ztp/internal/enricher_test.go
ztp/internal/models/properties.go

This patch changes the enricher so that it calculates default values for the `OC_OCP_TAG` and `OC_RCHOS_RELEASE` properties.

NO-ISSUE: Calculate OCP versions

---

ztp/go.mod
ztp/internal/cmd/create/cluster/create_cluster_cmd.go
ztp/internal/cmd/create/create_cmd.go
ztp/internal/cmd/create_cluster_cmd_test.go
ztp/internal/cmd/version_cmd_test.go
ztp/main.go

This patch renames the `edgecluster` command to `create cluster`.

NO-ISSUE: Rename `edgecluster` to `create cluster`

---

ztp/internal/cmd/create/cluster/create_cluster_cmd.go
ztp/internal/cmd/dev/cleanup/dev_cleanup_cmd.go
ztp/internal/cmd/dev/setup/dev_setup_cmd.go
ztp/internal/exit/error.go
ztp/main.go

This patch moves the `internal.ExitError` to a new `exit` package. That makes it more natural to use.

NO-ISSUE: Move exit error to separate package

---

ztp/internal/enricher.go
ztp/internal/enricher_test.go

Currently the enricher is setting the same CIDR for the cluster and machine networks. This patch fixes that.

NO-ISSUE: Fix overlaping CIDRs

---

ztp/go.mod
ztp/internal/data/cluster/objects/070-nmstateconfig.yaml
ztp/internal/enricher.go
ztp/internal/enricher_test.go

Currently the internal IP addresses aren't calculated correctly. That results in incorrect nmstate configurations that are rejected. This patch fixes that.

NO-ISSUE: Fix assignment of internal IP addresses

---

ztp/internal/data/cluster/objects/070-nmstateconfig.yaml
ztp/internal/enricher.go
ztp/internal/enricher_test.go
ztp/internal/models/nic.go

Currently the CLI generates the nmstate `prefix-lenght` field as a hexadecimal number, which is rejected. This patch fixes that changing it to a decimal number.

NO-ISSUE: Fix calculation of prefix length

---

ztp/internal/cmd/create_cluster_cmd_test.go
ztp/internal/data/dev/files/pull-secret.json
ztp/internal/data/dev/objects/0020-ingresscontroller.yaml
ztp/internal/enricher.go
ztp/internal/enricher_test.go

The DNS domain is currently copied from the configuration of the ingressc controller of the hub. For example, if that configuration is `apps.my-hub.my-domain.com` then the base DNS domain of the edge clusters will also be `apps.my-hub.my-domain.com`. But that is wrong; it should be only `my-domain.com`. This patch fixes that.

NO-ISSUE: Fix calculation of DNS domain

---

ztp/go.mod
ztp/internal/tool.go
ztp/internal/tool_test.go

This patch changes the tool so that it redirects 'klog' messages generated by the controller-runtime library to the log of the tool.

NO-ISSUE: Redirect klog to tool log

---

ztp/internal/data.go
ztp/internal/data/dev/crds/0015_agent.yaml
ztp/internal/enricher.go
ztp/internal/enricher_test.go
ztp/internal/gvks.go
ztp/internal/jq_test.go

This patch changes the enricher so that it fetchs the IP addresses of the external interfaces of the nodes of the clusters from the `Agent` objects, if they exist.

NO-ISSUE: Fetch external IP addresses from agents

---

ztp/internal/applier_test.go
ztp/internal/client.go
ztp/internal/enricher.go
ztp/internal/enricher_test.go
ztp/internal/models/cluster.go

This patch changes the enricher so that it gets the kubeconfig of the cluster from the `...-admin-kubeconfig` secret, if it exists.

NO-ISSUE: Get kubeconfig from secret

---

pipelines/resources/deploy-ztp-edgeclusters.yaml

New versions of openshift-pipeline require to explicitly set the task timemout after the switch from a generic `--timeout` to more granular timeouts: `--pipeline-timeout` and `--task-timeout`
- Versions:
- Hardware:

Set task timeout

---

ztp/internal/cmd/create/cluster/create_cluster_cmd.go
ztp/internal/cmd/create_cluster_cmd_test.go
ztp/internal/cmd/delete/cluster/delete_cluster_cmd.go
ztp/internal/config.go
ztp/internal/enricher.go
ztp/internal/enricher_test.go
ztp/internal/models/cluster.go
ztp/internal/models/config.go
ztp/internal/models/properties.go

Currently the tool expects the cluster image set in the `CLUSTERIMAGESET` environment variable, but this is just an itermediate variable used by the shell scripts, the value should be extracted from the configuration or calculated. This patch addresses that.
Tested with the included unit tests.

NO-ISSUE: Calculate image set

---

ztp/internal/client.go

Currently the code that creates the API client tries to get the `kube-public/cluster-info` configmap in order to check that the connection is working, but this doesn't work with OpenShift as that configmap doesn't exist. This patch removes that code.

NO-ISSUE: Don't try to get `cluster-info`

---

documentation/ztp-for-factories/ztp-install-factory-edge-pipeline.adoc
documentation/ztp-for-factories/ztp-install-factory-pipeline.adoc

Currently there are a couple of places in the documentation where the `-w` option of the `tnk pipeline start` command is missing the `name` part that indicates the name of the workspace. As a result those commands don't work. This patch fixes that.

NO-ISSUE: Fix use of `-w` without `name` in docs

---

ztp/internal/client.go
ztp/internal/cmd/create/cluster/create_cluster_cmd.go
ztp/internal/cmd/delete/cluster/delete_cluster_cmd.go
ztp/internal/cmd/dev/cleanup/dev_cleanup_cmd.go
ztp/internal/cmd/dev/setup/dev_setup_cmd.go
ztp/internal/enricher.go
ztp/internal/tool.go
ztp/main.go

Currently the the tool creates the Kubernetes API client loading the `KUBECONFIG` environment variable explicitly. This is done in order to generate better error messages, but it generates problems when running the tool in environments where the configuration has to come from other places, specially when it has to come from the secrets mounted inside a Kubernetes pod. To address this issue this patch changes the tool so that it uses the same mechanism used by tools like `kubectl`.

NO-ISSUE: Load Kubeconfig fron default locations

---

.github/workflows/check-cli.yml
ztp/Containerfile
ztp/go.mod

This patch changes the project to use Go 1.19 instead of 1.20, as that is what other OpenShift projects use.

NO-ISSUE: Downgrade to Go 1.19

---

images/Containerfile.pipeline

This patch changes the pipeline image so that it builds and includes the `ztp` binary.
Tested manually with `make build-pipe-image`.

NO-ISSUE: Add `ztp` binary to pipeline image

---

ztp/internal/cmd/create/cluster/create_cluster_cmd.go

Currently the `ztp` tool waits till the `Completed` condition of the agent cluster install has status `ready`, but that will never happen because the values are `True` or `False`. This patch fixes that.

NO-ISSUE: Fix cluster installed condition

---

ztp/internal/enricher.go
ztp/internal/enricher_test.go
ztp/internal/models/properties.go
ztp/internal/models/registry.go

This patch changes the enricher so that it fetches the CA certificates of the custom registry addresses specified in the `REGISTRY` property of the configuration.

NO-ISSUE: Fetch custom registry CA

---

ztp/internal/cmd/create_cluster_cmd_test.go
ztp/internal/data/cluster/objects/070-nmstateconfig.yaml
ztp/internal/data/cluster/objects/080-bmc-secret.yaml
ztp/internal/data/cluster/objects/090-baremetalhost.yaml
ztp/internal/models/cluster.go
ztp/internal/models/cluster_test.go
ztp/internal/models/node.go
ztp/internal/models/node_test.go
ztp/internal/models/suite_test.go

Currently if the name of a node in the configuration file is `master0` the resulting node name will be `ztpfw-...-master-master0`. That works fine for the creation of the cluster, but it breaks the scripts that run later to create the registry because they expect the nodes to be named `ztpfw-...-master-0`. It would be good to make that code independent of the names assiged to nodes, but for now we will instead change the CLI so that it generates the expected names.

NO-ISSUE: Fix naming of nodes

---

ztp/internal/cmd/dev/create/dev_create_cmd.go
ztp/internal/cmd/dev/delete/dev_delete_cmd.go
ztp/internal/cmd/dev/dev_cmd.go

This patch adds the `dev create` and `dev delete` files that can be used in the development environment to create and delete Kubernetes objects.

NO-ISSUE: Add utilities to create/delete objects

---

ztp/internal/data.go
ztp/internal/data/dev/crds/0011_icsp.yaml
ztp/internal/data/dev/crds/0080_olm.yaml

This patch adds to the development environment the custom resource definitions for the agent and for the image content source policy objects. Both will be needed to test the configuration of disconnected registries.

NO-ISSUE: Add agent and ICSP CRDs to dev env

---

ztp/internal/enricher.go
ztp/internal/enricher_test.go

Currently the enricher assumes that the IP addresses extracted from agents are something like `192.168.150.101` but they are like `192.168.150.101/24`. As a result they aren't detected correctly. This patch fixes that.

NO-ISSUE: Fix parsing IPs of agents

---

ztp/internal/cmd/suite_test.go
ztp/internal/logging/suite_test.go
ztp/internal/models/suite_test.go
ztp/internal/suite_test.go
ztp/internal/templating/suite_test.go

This patch changes the tests so that it redirect the `log` package to the `GinkgoWriter` to avoid interferences of logs generated by the http package.

NO-ISSUE: Avoid log package interferences with tests

---

ztp/internal/applier.go
ztp/internal/cmd/create/cluster/create_cluster_cmd.go
ztp/internal/cmd/delete/cluster/delete_cluster_cmd.go
ztp/internal/config/flags.go
ztp/internal/config/loader.go
ztp/internal/config/loader_test.go
ztp/internal/enricher.go
ztp/internal/jq/tool.go

Currently every command that needs the `--config` flag declares it separately. To avoid that repetition this patch moves that logic to a new `config.AddFlags` function.

NO-ISSUE: Add shared code to setup config flags

---

ztp/internal/applier.go
ztp/internal/cmd/delete/cluster/delete_cluster_cmd.go

Currently the `delete cluster` command deletes all the objects that `clreate cluster` creates. But the Hive cluster deployment can't be deleted because then Hive automatically deletes the namespace it contains. As a result the bare metal hosts can't be deleted successfully because the deletion process needs to create other objects inside the (now gone) namespace. To address that this patch changes the `delete cluster` command so that it doesn't delete the cluster deployment; it will be deleted automatically when the namespace is deleted.

NO-ISSUE: Don't explicitly delete cluster deployments

---

ztp/internal/cmd/create/cluster/create_cluster_cmd.go
ztp/internal/cmd/create_cluster_cmd_test.go

Currently the `create cluster` commands waits for the cluster to be installed, but it doesn't stop waiting if the installation fails. This patch fixes that.
Tested with the included tests.

NO-ISSUE: Stop waiting when cluster installation fails

---

ztp/go.mod
ztp/go.sum
ztp/internal/applier.go
ztp/internal/applier_test.go

Currently the code that waits for a CRD to be created fails occasionally because when a CRD is created and established it may not yet be available for use: the API server will keep responding with errors when trying to create objects of that type. In order to react better to that this patch changes the applier so that it repeatedly tries to create the object till the API server stops responding with the error that indicates that the CRD is not available.

NO-ISSUE: Improve wait for CRD

---

ztp/internal/data/cluster/files/api_hosts
ztp/internal/data/cluster/objects/030-agentclusterinstall.yaml
ztp/internal/data/metallb/objects/0100-metallb-api-ipaddresspool.yaml
ztp/internal/data/metallb/objects/0120-metallb-ingress-ipaddresspool.yaml
ztp/internal/enricher.go
ztp/internal/enricher_test.go
ztp/internal/models/api.go
ztp/internal/models/ingress.go

The internal ingress address is 192.168.7.242 and the internal API address is 192.168.7.243, but the CLI is using them swapped. This patch fixes that.

NO-ISSUE: Fix assignment of API and ingress addresses

---

ztp/internal/data/cluster/files/cluster-network-03-config.yml
ztp/internal/data/cluster/objects/020-manifests-configmap.yaml

This patch changes the `created edgecluster` command so that it sets the `routingViaHost: true` parameter using the installer configuration overriding mechanism. This parameter is needed later by the `create metallb` command, and it is also needed when the hosts only have one NIC.

NO-ISSUE: Route via hosts

---

ztp/internal/logging/flags.go
ztp/internal/logging/logger.go
ztp/internal/logging/logger_test.go
ztp/internal/logging/transport_wrapper.go

This patch adds command line options that add custom log fields. For example, to add a field with name `user` containing the user name:
```
$ ztp create cluster -c my-config.yaml --log-field "user=${USER}"
```
This is intended for situations where multiple processes write to the same file. Adding these fields it is easier to identify which process is the one that wrote a particular log message. In that context it is specially useful to add the PID of the proccess. The special value `%p` is used for that:
```
$ ztp create cluster -c my-config.yaml --log-field pid=%p
```
Or just `%p`, without the `pid=` prefix:
```
$ ztp create cluster -c my-config.yaml --log-field %p
```
Note that before this patch the `pid` field was always added, now it isn't added by default.
Please select the …

NO-ISSUE: Add support for custom log fields

---

ztp/internal/client.go
ztp/internal/client_test.go
ztp/internal/cmd/create/cluster/create_cluster_cmd.go
ztp/internal/cmd/create/metallb/create_metallb_cmd.go
ztp/internal/cmd/delete/cluster/delete_cluster_cmd.go
ztp/internal/cmd/dev/apply/dev_apply_cmd.go
ztp/internal/cmd/dev/cleanup/dev_cleanup_cmd.go
ztp/internal/cmd/dev/delete/dev_delete_cmd.go
ztp/internal/cmd/dev/setup/dev_setup_cmd.go
ztp/internal/logging/flags.go
ztp/internal/logging/logger.go
ztp/internal/logging/transport_wrapper.go
ztp/internal/logging/transport_wrapper_test.go

Currently when log level 2 is enabled we write to the log all the details of HTTP requests and responses, including HTTP headers and sizes of HTTP request and response bodies. This is quite noisy, and usually not necessary. This patch adds two new flags `--log-headers=[true|fase]` and `--log-bodies=[true|false]` that allow selectively enabling/disabling those details.

NO-ISSUE: Add options to enable/disable HTTP logging

---

ztp/internal/data/metallb/objects/0150-nncp.yaml

Currently the node selectors of the node network configuration policies generated for metal load balancers use the name of the node, but they should use the host names instead. This patch fixes that.

NO-ISSUE: Fix selectors of node network configuration policies

---

ztp/internal/console.go
ztp/internal/console_flags.go
ztp/internal/tool.go

This patch adds a `--color` flag that can be used to explicitly enable/disable use of color in the console.

NO-ISSUE: Add `--color` flag

---

ztp/internal/cmd/create/create_cmd.go
ztp/internal/cmd/create/icsp/create_icsp_cmd.go
ztp/internal/data/dev/objects/0050-marketplace-namespace.yaml
ztp/internal/data/dev/objects/0060-catalog-sources.yaml
ztp/internal/data/dev/objects/0070-registry-namespace.yaml
ztp/internal/data/dev/objects/0080-registry-configmap.yaml
ztp/internal/gvks.go

This patch adds a new `create icsp` command that reads the catalog sources and registry configuration from the hub cluster and creates image content source policies in the edge cluster so that images are pulled from the hub registry.

NO-ISSUE: Add `create icsp` command

---

ztp/internal/cmd/create/icsp/create_icsp_cmd.go
ztp/internal/data.go
ztp/internal/data/dev/crds/0012_image.yaml
ztp/internal/data/dev/objects/0080-registry-configmap.yaml
ztp/internal/data/dev/objects/image-config.yaml
ztp/internal/enricher.go
ztp/internal/enricher_test.go
ztp/internal/gvks.go

This patch changes the `create icsp` command so that it changes the image pull configuration of the cluster to trust the CA of the registry.

NO-ISSUE: Trust registry

---

ztp/internal/data/cluster/objects/070-nmstateconfig.yaml
ztp/internal/data/cluster/objects/080-bmc-secret.yaml
ztp/internal/data/cluster/objects/090-baremetalhost.yaml

Currently the templates that calculate the names for the bare metal hosts and for the BMC secrets explicitly. This patch changes them so that they use the `Hostname` property of the host instead.

NO-ISSUE: Use calculated hostname for BMH and BMC secrets

---

ztp/internal/data/cluster/files/add-internal-ip-bmh.sh

Currently one a node has only one NIC we add the internal IP address to the external NIC, but that doesn't work correctly: it needs to be added to the `br-ex` bridge that is used by OVS.

NO-ISSUE: Add internal IP to `br-ex`

---

pipelines/resources/deploy-ztp-edgeclusters-connected.yaml
pipelines/resources/deploy-ztp-edgeclusters-sno-connected.yaml
pipelines/resources/deploy-ztp-edgeclusters-sno.yaml
pipelines/resources/deploy-ztp-edgeclusters.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-edgecluster.yaml

This patch changes the `deploy-edgecluster` step of the pipeline so that it executes the `ztp` binary instead of shell scripts.
Related: https://issues.redhat.com/browse/MGMT-13114
Fixes MGMT-13114.

MGMT-13114: Replace `deploy-edgecluster` scripts with `ztp`

---

.github/workflows/check-pipelines.yml

This patch adds a GitHub action that checks the syntas of the Tekton pipelines. It does so by installing a Kind cluster, installing Tekton inside and then creating the pipelines. If there are syntax errors in the pipelines that last step will fail.

NO-ISSUE: Check pipelines

---

pipelines/resources/deploy-ztp-edgeclusters.yaml

The patch that introduced the `ztp-log-level` parameter duplicated it in the `deploy-ztp-egeclusters` pipeline. This patch fixes that.

NO-ISSUE: Remove duplicated `ztp-log-level` parameter

---

ztp/internal/enricher.go
ztp/internal/logging/flags.go
ztp/internal/logging/logger.go
ztp/internal/logging/logger_test.go
ztp/internal/logging/sink.go

This patch adds the capability to redact security sensitive fields from the logs. Those fields will be marked with an exclamation mark prefix, and will be redacted by default. For example:
```go
logger.Info(
"SSH keys",
"public", publicKey,
"!private", privateKey,
)
```
Will generate a log message like this:
```json
{
"msg": "SSH keys",
"public": "ssh-rsa AAA...",
"private": "***"
}
```
Redacting can be enabled with the new `--log-redact=[true|false]` command line option.

NO-ISSUE: Redact security sensitive log fields

---

ztp/internal/client.go
ztp/internal/cmd/create/metallb/create_metallb_cmd.go
ztp/internal/cmd/delete/metallb/delete_metallb_cmd.go

This patch changes the `ztp delete metallb` so that it also deletes the CRDs in the groups `metalb.io` and `nmstate.io` groups if the `--crds=true` option is used. This is intended for use in development environments where it is convenient to completely delete them to be able to fully test the `ztp create metallb` command.

NO-ISSUE: Delete CRDs when deleting metal load balancer

---

ztp/internal/cmd/delete/delete_cmd.go
ztp/internal/cmd/delete/lso/delete_lso_cmd.go
ztp/internal/data/lso/objects/0020-operatorgroup.yaml
ztp/internal/data/lso/objects/0030-subscription.yaml
ztp/internal/data/lso/objects/0040-localvolume.yaml

This patch adds a new `ztp delete lso` command that deletes the objects created by the `ztp create lso` command. This is intended for use in development environments, where it is convenient ro un the create command multiple times without having to manually delete the objects or else create the cluster from scratch.

NO-ISSUE: Add `delete lso` command

---

ztp/internal/client.go
ztp/internal/client_test.go
ztp/internal/logging/transport_wrapper.go
ztp/internal/logging/transport_wrapper_test.go

The Kubernetes API client sends multiple initial requestst to retrieve metadata. These don't provide any useful information and pollute the log. This patch changes the logger so that it discards these requests.

NO-ISSUE: Supress noise HTTP logs

---

ztp/internal/cmd/lso/create_lso_cmd.go
ztp/internal/cmd/lso/delete_lso_cmd.go

When the `create lso` and `delete lso` commands were moved to the same packaged an error was introduced that makes the `create lso` command execute the logic of the `delete lso` command. This patch fixes that issue.

NO-ISSUE: Fix `create lso` command

---

ztp/internal/client.go
ztp/internal/client_test.go

This patch fixes the regular expressions used by the API client to exclude metadata requests.
Tested with the included unit tests.

NO-ISSUE: Fix API client log filter

---

ztp/internal/client.go
ztp/internal/logging/sink.go

When the API server is restarted the existing watches are closed, and trying to start them again may result in requesting a resource version that is too old and has alreayd been forgotten/compacted by etcd. That results in receiving an `ERROR` event with code `420 Gone` indicating that the resource version is too old. In that situation the CLI currently just tries to create the watch again, but using the same resource version. That results into an infinite loop. This patch fixes that issue. When the CLI receives the `ERROR` event it will restart the watch from version `0`.

MGMT-13924: Restart watches when API server is restarted

---

ztp/internal/applier.go
ztp/internal/cmd/cluster/create_cluster_cmd.go

The watches that we create to wait for cluster installation to be completed don't need to process the bookmark events because they are already processed by the unerlying watch. Processing them produces incorrect results because those events don't contain any event data, only the resource version. This patch changes those watches so that they ingore bookmark events.

NO-ISSUE: Ignore bookmark events

---

pipelines/resources/deploy-ztp-edgeclusters-connected.yaml
pipelines/resources/deploy-ztp-edgeclusters-sno-connected.yaml
pipelines/resources/deploy-ztp-edgeclusters-sno.yaml
pipelines/resources/deploy-ztp-edgeclusters.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-edgecluster.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-icsp-edgeclusters-pre.yaml
pipelines/resources/edgeclusters/edgecluster-deploy-metallb.yaml

This patch changes the pipelines to use the `ztp` CLI in the `metallb` steps instead of the shell scripts.
Related: https://issues.redhat.com/browse/MGMT-13116

MGMT-13116: Use the CLI in the `metallb` step

---

ztp/internal/annotations/annotations.go
ztp/internal/cmd/lso/create_lso_cmd.go
ztp/internal/cmd/lso/delete_lso_cmd.go

This patch removes the `--wipe` option of the `create lso` command. Instead of requiring that option the command will write a `ztpfw/wiped: true|false` annotation in the namespace of the cluster. If the annotation exists it will not do the wiping. If the annotation doesn't exist it will do the wiping and add the annotation. This makes the command idempotent.
Related: https://issues.redhat.com/browse/MGMT-13974

MGMT-13974: Remove `--wipe` option of `create lso`

---

ztp/internal/client.go
ztp/internal/client_test.go
ztp/internal/cmd/lso/create_lso_cmd.go
ztp/internal/cmd/lso/delete_lso_cmd.go
ztp/internal/cmd/odf/create_odf_cmd.go

This patch adds to the Kubernetes client object methods that simplify adding labels and annotations.

NO-ISSUE: Simplify labeling and annotating

---

ztp/internal/cmd/icsp/create_icsp_cmd.go
ztp/internal/registry_tool.go
ztp/internal/registry_tool_test.go

This patch adds a new `RegistryTool` object that simplifies certain image registry tasks. For example, it simplifies adding a trusted registry CA to an OpenShift cluster.

NO-ISSUE: Add registry tool

---

ztp/internal/registry_tool.go

This patch removes the warning that the registry tool generates when custom object names are used. That doesn't work because the checked names will always have a value, even if it is the default. There is not much value in that chec, so it is OK to remove it.

NO-ISSUE: Remove warn of custom names in registry tool

---

ztp/internal/cmd/icsp/create_icsp_cmd.go
ztp/internal/registry_tool.go
ztp/internal/registry_tool_test.go

This patch adds to the registry tool the capability to check if a registry is already trusted. This will be used to avoid changing the configuration when it is already modified.

NO-ISSUE: Improve registry tool

---

pipelines/resources/deploy-ztp-edgeclusters-connected.yaml
pipelines/resources/deploy-ztp-edgeclusters.yaml

In pull request #162 we removed the step to deploy worker nodes from the pipeline because with OpenShift 4.12 it is no longer necessary: the worker nodes can be created from the beginning. But the fixes needed to support that were done only to the CLI, which was since then removed from the pipeline. This patch reverts those changes to the pipeline.
Related: https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/pull/162

NO-ISSUE: Revert remove deploy workers
